
INSERT INTO Color (id,color,description,createdAt,updatedAt) VALUES
 ('1','White','ابيض',NOW(),NOW()),
  ('2','Black','اسود',NOW(),NOW()),
  ('3','Dark Gray','رمادي غامق',NOW(),NOW()),
 ('4','Red','أحمر',NOW(),NOW()),
 ('5','Green','أخضر',NOW(),NOW()),
 ('6','Blue','أزرق',NOW(),NOW()),
 ('7','Gray','رمادي',NOW(),NOW()),
 ('8','Silver','فضي',NOW(),NOW()),
 ('9','Orange','البرتقالي',NOW(),NOW()),
 ('10','Brown','بنى',NOW(),NOW()),
 ('11','Cream','كريم',NOW(),NOW()),
 ('12','Yellow','أصفر',NOW(),NOW()),
 ('13','Pink','وردي',NOW(),NOW()),
 ('14','Violet','البنفسجي',NOW(),NOW()),
 ('15','Dark Red','احمر غامق',NOW(),NOW()),
 ('16','Dark Brown','بني غامق',NOW(),NOW()),
 ('17','Beige','اللون البيج',NOW(),NOW()),
 ('18','Maroon','كستنائي',NOW(),NOW()),
 ('19','Dark Green','أخضر غامق',NOW(),NOW()),
 ('20','Dark Blue','ازرق غامق',NOW(),NOW()),
 ('21','Light green','اخضر فاتح',NOW(),NOW()),
 ('22','Light yellow ','أصفر فاتح',NOW(),NOW()),
 ('23','Light red','الضوء الأحمر',NOW(),NOW()),
 ('24','Dark gray','الرمادي الداكن',NOW(),NOW()),
 ('25','Light brown','البني الفاتح',NOW(),NOW()),
 ('26','Light blue','أزرق فاتح',NOW(),NOW()),
 ('27','Dark black','أسود مظلم',NOW(),NOW()),
 ('28','Dark yellow','اصفر غامق',NOW(),NOW()),
 ('29','Golden ','ذهبي',NOW(),NOW()),
 ('30','Golden yellow','أصفر ذهبي',NOW(),NOW()),
 ('31','Golden brown','بني ذهبي',NOW(),NOW()),
 ('32','White/Red','أبيض أحمر',NOW(),NOW()),
 ('33','White/Black','أبيض أسود',NOW(),NOW()),
 ('34','White/Green','لأخضر الأبيض',NOW(),NOW()),
 ('35','White/Blue','أزرق أبيض',NOW(),NOW()),
 ('36','White/Gray','لرمادي الأبيض',NOW(),NOW()),
 ('37','White/Silver','الفضة البيضاء',NOW(),NOW()),
 ('38','White/Orange','البرتقال الأبيض',NOW(),NOW()),
 ('39','White/Brown','البني الأبيض',NOW(),NOW()),
 ('40','White/Cream','كريم أبيض',NOW(),NOW()),
 ('41','White/Yellow','أبيض أصفر',NOW(),NOW()),
 ('42','White/Pink','أبيض وردي',NOW(),NOW()),
 ('43','White/Violet','البنفسجي الأبيض',NOW(),NOW()),
 ('44','Black/Red','أسود أحمر',NOW(),NOW()),
 ('45','Black/Green','الأخضر الأسود',NOW(),NOW()),
 ('46','Black/Blue','أزرق مسود',NOW(),NOW()),
 ('47','Black/Gray','أسود اللون الرمادي',NOW(),NOW()),
 ('48','Black/Silver','الفضة السوداء',NOW(),NOW()),
 ('49','Black/Brown','أسود اللون البني',NOW(),NOW()),
 ('50','Black/Yellow','أسود الأصفر',NOW(),NOW()),
 ('51','Green/Red','أخضر أحمر',NOW(),NOW()),
 ('52','Green/Blue','أخضر أزرق',NOW(),NOW()),
 ('53','Green/Yellow','اصفر مخضر',NOW(),NOW()),
 ('54','Green/Silver','الفضة الخضراء',NOW(),NOW()),
 ('55','Blue/Gray','ازرق رمادي',NOW(),NOW()),
 ('56','Blue/Silver','الفضة الزرقاء',NOW(),NOW()),
 ('57','Blue/Black','أزرق أسود',NOW(),NOW()),
 ('58','Blue/Beige','البيج الأزرق',NOW(),NOW()),
 ('59','Dark Golden','ذهبي غامق',NOW(),NOW()),
 ('60','Blue/Orange','أزرق / برتقالي',NOW(),NOW()),
 ('61','Dark/Silver','رصاصي غامق',NOW(),NOW()),
 ('62','D.Blue/Black','ازرق غامق / اسود',NOW(),NOW()),
 ('63','Orange/Black','البرتقالي/الاسود',NOW(),NOW())
