INSERT INTO elabJed.VehicleManufacturer (id, name, description, country, createdAt, updatedAt) VALUES
	('1', 'DAEWOO', 'DAEWOO', 'كوريا الجنوبية', now(), now()),
	('2', 'MERCEDES BENZ', 'MERCEDES BENZ', 'ألمانيا', now(), now()),
	('3', 'CHERY', 'CHERY', 'الصين', now(), now()),
	('4', 'BENTLY', 'BENTLY', 'المملكة المتحدة', now(), now()),
	('5', 'ASTON MARTIN', 'ASTON MARTIN', 'المملكة المتحدة', now(), now()),
	('6', 'BRILLIANCE', 'BRILLIANCE', 'الصين', now(), now()),
	('7', 'BYD', 'BYD', 'الصين', now(), now()),
	('8', 'AUDI', 'AUDI', 'ألمانيا', now(), now()),
	('9', 'MERCURY', 'MERCURY', 'الولايات المتحدة الأمريكية', now(), now()),
	('10', 'MASERATI', 'MASERATI', 'إيطاليا', now(), now()),
	('11', 'CHANGAN', 'CHANGAN', 'الصين', now(), now()),
	('12', 'ACURA', 'ACURA', 'اليابان', now(), now()),
	('13', 'ROLLS ROYS', 'ROLLS ROYS', 'المملكة المتحدة', now(), now()),
	('14', 'VOLKSWAGEN', 'VOLKSWAGEN', 'ألمانيا', now(), now()),
	('15', 'TATA', 'TATA', 'الهند', now(), now()),
	('16', 'PORSCHE', 'PORSCHE', 'ألمانيا', now(), now()),
	('17', 'RENAULT', 'RENAULT', 'فرنسا', now(), now()),
	('18', 'SEAT', 'SEAT', 'إسبانيا', now(), now()),
	('19', 'SMART', 'SMART', 'ألمانيا', now(), now()),
	('20', 'VOLVO', 'VOLVO', 'السويد', now(), now()),
	('22', 'OPEL', 'OPEL', 'ألمانيا', now(), now()),
	('23', 'MAYBACH', 'MAYBACH', 'ألمانيا', now(), now()),
	('24', 'LINCOLN', 'LINCOLN', 'الولايات المتحدة الأمريكية', now(), now()),
	('25', 'SAAB', 'SAAB', 'السويد', now(), now()),
	('26', 'SCION', 'SCION', 'اليابان', now(), now()),
	('27', 'PAGANI', 'PAGANI', 'إيطاليا', now(), now()),
	('28', 'NOBLE', 'NOBLE', 'المملكة المتحدة', now(), now()),
	('29', 'OLDSMOBILE', 'OLDSMOBILE', 'الولايات المتحدة الأمريكية', now(), now()),
	('30', 'MORGAN', 'MORGAN', 'المملكة المتحدة', now(), now()),
	('31', 'MG', 'MG', 'الصين', now(), now()),
	('32', 'MCLAREN', 'MCLAREN', 'المملكة المتحدة', now(), now()),
	('33', 'LOTUS', 'LOTUS', 'المملكة المتحدة', now(), now()),
	('34', 'PONTIAC', 'PONTIAC', 'الولايات المتحدة الأمريكية', now(), now()),
	('35', 'PLYMOUTH', 'PLYMOUTH', 'الولايات المتحدة الأمريكية', now(), now()),
	('36', 'RAM', 'RAM', 'الولايات المتحدة الأمريكية', now(), now()),
	('37', 'HAMMER', 'HAMMER', 'الولايات المتحدة الأمريكية', now(), now()),
	('39', 'DATSUN', 'DATSUN', 'اليابان', now(), now()),
	('40', 'BAIC', 'BAIC', 'الصين', now(), now()),
	('41', 'DFM', 'DFM', 'الصين', now(), now()),
	('42', 'HAFEI', 'HAFEI', 'الصين', now(), now()),
	('43', 'JONWAY', 'JONWAY', 'الصين', now(), now()),
	('44', 'KARRY', 'KARRY', 'الصين', now(), now()),
	('45', 'SSANG YONG', 'SSANG YONG', 'الصين', now(), now()),
	('46', 'ZOTYE', 'ZOTYE', 'الصين', now(), now()),
	('47', 'SATURN', 'SATURN', 'الولايات المتحدة الأمريكية', now(), now()),
	('48', 'EAGLE', 'EAGLE', 'الولايات المتحدة الأمريكية', now(), now()),
	('49', 'FIAT', 'FIAT', 'إيطاليا', now(), now()),
	('50', 'EMGRAND', 'EMGRAND', 'الصين', now(), now()),
	('51', 'FAW', 'FAW', 'الصين', now(), now()),
	('52', 'GEELY', 'GEELY', 'الصين', now(), now()),
	('53', 'GREAT WALL', 'GREAT WALL', 'الصين', now(), now()),
	('54', 'GAC', 'GAC', 'الصين', now(), now()),
	('55', 'FOTON', 'FOTON', 'الصين', now(), now()),
	('56', 'JAC', 'JAC', 'الصين', now(), now()),
	('57', 'FOISON', 'FOISON', 'الصين', now(), now()),
	('58', 'LANCIA', 'LANCIA', 'إيطاليا', now(), now()),
	('60', 'ZNA', 'ZNA', 'الصين', now(), now()),
	('61', 'SOUEAST', 'SOUEAST', 'الصين', now(), now()),
	('62', 'SPERANZA', 'SPERANZA', 'الصين', now(), now()),
	('65', 'PROTON', 'PROTON', 'ماليزيا', now(), now()),
	('66', 'SENOVA', 'SENOVA', 'الصين', now(), now()),
	('67', 'MORRIS GARAGE', 'MORRIS GARAGE', 'المملكة المتحدة', now(), now()),
	('68', 'MAHINDRA', 'MAHINDRA', 'الهند', now(), now()),
	('69', 'LADA', 'LADA', 'روسيا', now(), now()),
	('71', 'GAZ', 'GAZ', 'روسيا', now(), now()),
	('72', 'CITROEN', 'CITROEN', 'فرنسا', now(), now()),
	('75', 'HHHH', 'HHHH', 'الصين', now(), now()),
	('76', 'B.M.W', 'B.M.W', 'ألمانيا', now(), now()),
	('77', 'TOYOTA', 'TOYOTA', 'اليابان', now(), now()),
	('78', 'NISSAN', 'NISSAN', 'اليابان', now(), now()),
	('79', 'BUGATTI', 'BUGATTI', 'فرنسا', now(), now()),
	('80', 'BUICK', 'BUICK', 'الولايات المتحدة الأمريكية', now(), now()),
	('81', 'CADILLAC', 'CADILLAC', 'الولايات المتحدة الأمريكية', now(), now()),
	('82', 'CHRYSLER', 'CHRYSLER', 'الولايات المتحدة الأمريكية', now(), now()),
	('83', 'DODGE', 'DODGE', 'الولايات المتحدة الأمريكية', now(), now()),
	('84', 'DAF', 'DAF', 'هولندا', now(), now()),
	('85', 'GMC', 'GMC', 'الولايات المتحدة الأمريكية', now(), now()),
	('86', 'FORD', 'FORD', 'الولايات المتحدة الأمريكية', now(), now()),
	('87', 'FERRARI', 'FERRARI', 'إيطاليا', now(), now()),
	('88', 'JEEP', 'JEEP', 'الولايات المتحدة الأمريكية', now(), now()),
	('89', 'HONDA', 'HONDA', 'اليابان', now(), now()),
	('90', 'HYUNDAI', 'HYUNDAI', 'كوريا الجنوبية', now(), now()),
	('91', 'KIA', 'KIA', 'كوريا الجنوبية', now(), now()),
	('92', 'MITSUBISHI', 'MITSUBISHI', 'اليابان', now(), now()),
	('93', 'MINI COOPER', 'MINI COOPER', 'ألمانيا', now(), now()),
	('94', 'LAMBORGINI', 'LAMBORGINI', 'إيطاليا', now(), now()),
	('95', 'SCODA', 'SCODA', 'جمهورية التشيك', now(), now()),
	('96', 'GINJO', 'GINJO', 'الصين', now(), now()),
	('97', 'ROLLS ROYCE', 'ROLLS ROYCE', 'المملكة المتحدة', now(), now()),
	('98', 'JAGUAR', 'JAGUAR', 'المملكة المتحدة', now(), now()),
	('99', 'MAN', 'MAN', 'ألمانيا', now(), now()),
	('100', 'INTERNATIONAL', 'INTERNATIONAL', 'الولايات المتحدة الأمريكية', now(), now()),
	('101', 'MASERATTI', 'MASERATTI', 'إيطاليا', now(), now()),
	('102', 'PETERBILT', 'PETERBILT', 'الولايات المتحدة الأمريكية', now(), now()),
	('103', 'HINO', 'HINO', 'اليابان', now(), now()),
	('104', 'CHEVROLET', 'CHEVROLET', 'الولايات المتحدة الأمريكية', now(), now()),
	('105', 'LAND ROVER', 'LAND ROVER', 'المملكة المتحدة', now(), now()),
	('106', 'LEXUS', 'LEXUS', 'اليابان', now(), now()),
	('107', 'MAZDA', 'MAZDA', 'اليابان', now(), now()),
	('108', 'IVECO', 'IVECO', 'إيطاليا', now(), now()),
	('109', 'PEUGEOT', 'PEUGEOT', 'فرنسا', now(), now()),
	('110', 'CLA250', 'CLA250', 'ألمانيا', now(), now()),
	('112', 'E1', 'E1', 'الولايات المتحدة الأمريكية', now(), now()),
	('113', 'SUBARU', 'SUBARU', 'اليابان', now(), now()),
	('114', 'DAIHATSU', 'DAIHATSU', 'اليابان', now(), now()),
	('115', 'CARAVAN', 'CARAVAN', 'الولايات المتحدة الأمريكية', now(), now()),
	('116', 'MOTOR HOME', 'MOTOR HOME', 'الولايات المتحدة الأمريكية', now(), now()),
	('117', 'G63 AMG', 'G63 AMG', 'ألمانيا', now(), now()),
	('118', 'INFINITI', 'INFINITI', 'اليابان', now(), now()),
	('119', 'SUNLONG', 'SUNLONG', 'الصين', now(), now()),
	('120', 'CHTC', 'CHTC', 'الولايات المتحدة الأمريكية', now(), now()),
	('121', 'ASTRA', 'ASTRA', 'روسيا', now(), now()),
	('122', 'REWARD', 'REWARD', 'الصين', now(), now()),
	('123', 'IZUSU', 'IZUSU', 'اليابان', now(), now()),
	('125', 'LIFAN', 'LIFAN', 'الصين', now(), now()),
	('126', 'UAZ', 'UAZ', 'الصين', now(), now()),
	('127', 'SCANIA', 'SCANIA', 'السويد', now(), now()),
	('128', 'GENESIS', 'GENESIS', 'كوريا الجنوبية', now(), now()),
	('129', 'YUTONG', 'YUTONG', 'الصين', now(), now()),
	('130', 'ASIASTAR', 'ASIASTAR', 'الصين', now(), now()),
	('131', 'MINI', 'MINI', 'ألمانيا', now(), now()),
	('132', 'SINOTRUCK', 'SINOTRUCK', 'الصين', now(), now());