INSERT INTO VehicleType (id, modelType, description, manufacturerId, createdAt, updatedAt) VALUES
	(uuid(), 'CIELO', 'CIELO', '1', now(), now()),
	(uuid(), 'ESPERO', 'ESPERO', '1', now(), now()),
	(uuid(), 'JULIET', 'JULIET', '1', now(), now()),
	(uuid(), 'LACETTI', 'LACETTI', '1', now(), now()),
	(uuid(), 'LANOS', 'LANOS', '1', now(), now()),
	(uuid(), 'LEGANZA', 'LEGANZA', '1', now(), now()),
	(uuid(), 'LEMANS', 'LEMANS', '1', now(), now()),
	(uuid(), 'MATIZ', 'MATIZ', '1', now(), now()),
	(uuid(), 'NUBIRA', 'NUBIRA', '1', now(), now()),
	(uuid(), 'RACER', 'RACER', '1', now(), now()),
	(uuid(), 'TICO', 'TICO', '1', now(), now()),
	(uuid(), 'ZAZ', 'ZAZ', '1', now(), now()),
	(uuid(), 'CONCRETE PUMP', 'CONCRETE PUMP', '1', now(), now()),
	(uuid(), 'CONCRETE MIXER', 'CONCRETE MIXER', '1', now(), now()),
	(uuid(), '36RX', '36RX', '1', now(), now()),
	(uuid(), 'CLA Class Coupe', 'CLA Class Coupe', '2', now(), now()),
	(uuid(), 'CLS Class Coupe', 'CLS Class Coupe', '2', now(), now()),
	(uuid(), 'E Class Cabriolet', 'E Class Cabriolet', '2', now(), now()),
	(uuid(), 'E Class Coupe', 'E Class Coupe', '2', now(), now()),
	(uuid(), 'E Class Sedan', 'E Class Sedan', '2', now(), now()),
	(uuid(), 'E Class Wagon', 'E Class Wagon', '2', now(), now()),
	(uuid(), 'GL Class SUV', 'GL Class SUV', '2', now(), now()),
	(uuid(), 'G Class SUV', 'G Class SUV', '2', now(), now()),
	(uuid(), 'GLA Class SUV', 'GLA Class SUV', '2', now(), now()),
	(uuid(), 'GLK Class SUV', 'GLK Class SUV', '2', now(), now()),
	(uuid(), 'M Class SUV', 'M Class SUV', '2', now(), now()),
	(uuid(), 'S Class Coupe', 'S Class Coupe', '2', now(), now()),
	(uuid(), 'S Class Sedan', 'S Class Sedan', '2', now(), now()),
	(uuid(), 'SL Class Roadster', 'SL Class Roadster', '2', now(), now()),
	(uuid(), 'SLK Class Roadster', 'SLK Class Roadster', '2', now(), now()),
	(uuid(), '190 Series', '190 Series', '2', now(), now()),
	(uuid(), '200 Series', '200 Series', '2', now(), now()),
	(uuid(), '240 Series', '240 Series', '2', now(), now()),
	(uuid(), '260 Series', '260 Series', '2', now(), now()),
	(uuid(), '280 Series', '280 Series', '2', now(), now()),
	(uuid(), '300 Series', '300 Series', '2', now(), now()),
	(uuid(), '380 Series', '380 Series', '2', now(), now()),
	(uuid(), '400 Series', '400 Series', '2', now(), now()),
	(uuid(), '420 Series', '420 Series', '2', now(), now()),
	(uuid(), '500 Series', '500 Series', '2', now(), now()),
	(uuid(), '560 Series', '560 Series', '2', now(), now()),
	(uuid(), '600 Series', '600 Series', '2', now(), now()),
	(uuid(), 'B –Class', 'B –Class', '2', now(), now()),
	(uuid(), 'CLA-Class', 'CLA-Class', '2', now(), now()),
	(uuid(), 'CLK-Class', 'CLK-Class', '2', now(), now()),
	(uuid(), 'SLR McLaren', 'SLR McLaren', '2', now(), now()),
	(uuid(), 'Sprinter', 'Sprinter', '2', now(), now()),
	(uuid(), 'Metris Cargo Van', 'Metris Cargo Van', '2', now(), now()),
	(uuid(), 'ML 350', 'ML 350', '2', now(), now()),
	(uuid(), 'ACTROS 3241', 'ACTROS 3241', '2', now(), now()),
	(uuid(), 'ACTROS 1841', 'ACTROS 1841', '2', now(), now()),
	(uuid(), 'ACTROS 1844', 'ACTROS 1844', '2', now(), now()),
	(uuid(), 'ACTROS1840', 'ACTROS1840', '2', now(), now()),
	(uuid(), 'ACTROS 1843', 'ACTROS 1843', '2', now(), now()),
	(uuid(), 'ACTROS 3341', 'ACTROS 3341', '2', now(), now()),
	(uuid(), '2532', '2532', '2', now(), now()),
	(uuid(), '2546', '2546', '2', now(), now()),
	(uuid(), 'C 300', 'C 300', '2', now(), now()),
	(uuid(), 'E 300', 'E 300', '2', now(), now()),
	(uuid(), 'E 350', 'E 350', '2', now(), now()),
	(uuid(), 'C 350', 'C 350', '2', now(), now()),
	(uuid(), '2541', '2541', '2', now(), now()),
	(uuid(), '3241', '3241', '2', now(), now()),
	(uuid(), '1841', '1841', '2', now(), now()),
	(uuid(), '2644', '2644', '2', now(), now()),
	(uuid(), 'MIXER', 'MIXER', '2', now(), now()),
	(uuid(), '2544', '2544', '2', now(), now()),
	(uuid(), '3236', '3236', '2', now(), now()),
	(uuid(), 'LARGE TRUCK.', 'LARGE TRUCK.', '2', now(), now()),
	(uuid(), '4141', '4141', '2', now(), now()),
	(uuid(), 'C 220', 'C 220', '2', now(), now()),
	(uuid(), 'GLK 350.', 'GLK 350.', '2', now(), now()),
	(uuid(), '2044', '2044', '2', now(), now()),
	(uuid(), 'S 500', 'S 500', '2', now(), now()),
	(uuid(), 'S 550', 'S 550', '2', now(), now()),
	(uuid(), '4144', '4144', '2', now(), now()),
	(uuid(), '3344', '3344', '2', now(), now()),
	(uuid(), '1836', '1836', '2', now(), now()),
	(uuid(), '2536', '2536', '2', now(), now()),
	(uuid(), '2636', '2636', '2', now(), now()),
	(uuid(), 'C 400', 'C 400', '2', now(), now()),
	(uuid(), 'E 550', 'E 550', '2', now(), now()),
	(uuid(), '328', '328', '2', now(), now()),
	(uuid(), 'LARGE BUS', 'LARGE BUS', '2', now(), now()),
	(uuid(), '2632', '2632', '2', now(), now()),
	(uuid(), 'VIANO', 'VIANO', '2', now(), now()),
	(uuid(), 'S 400', 'S 400', '2', now(), now()),
	(uuid(), 'S 300', 'S 300', '2', now(), now()),
	(uuid(), 'S 63', 'S 63', '2', now(), now()),
	(uuid(), 'E 200', 'E 200', '2', now(), now()),
	(uuid(), 'C 250', 'C 250', '2', now(), now()),
	(uuid(), '1832', '1832', '2', now(), now()),
	(uuid(), 'GL 550', 'GL 550', '2', now(), now()),
	(uuid(), 'CLS 550', 'CLS 550', '2', now(), now()),
	(uuid(), 'GT S', 'GT S', '2', now(), now()),
	(uuid(), 'FREIGHTLINER', 'FREIGHTLINER', '2', now(), now()),
	(uuid(), '1844', '1844', '2', now(), now()),
	(uuid(), '2641', '2641', '2', now(), now()),
	(uuid(), '3331', '3331', '2', now(), now()),
	(uuid(), 'CLA250', 'CLA250', '2', now(), now()),
	(uuid(), '4151', '4151', '2', now(), now()),
	(uuid(), 'CLA 200', 'CLA 200', '2', now(), now()),
	(uuid(), '2036', '2036', '2', now(), now()),
	(uuid(), '3341', '3341', '2', now(), now()),
	(uuid(), '2548', '2548', '2', now(), now()),
	(uuid(), 'SL500', 'SL500', '2', now(), now()),
	(uuid(), 'C180', 'C180', '2', now(), now()),
	(uuid(), 'S500', 'S500', '2', now(), now()),
	(uuid(), 'G63 AMG', 'G63 AMG', '2', now(), now()),
	(uuid(), '3332', '3332', '2', now(), now()),
	(uuid(), 'E300', 'E300', '2', now(), now()),
	(uuid(), 'GLE400', 'GLE400', '2', now(), now()),
	(uuid(), '0710', '0710', '2', now(), now()),
	(uuid(), '3244', '3244', '2', now(), now()),
	(uuid(), 'CLS63', 'CLS63', '2', now(), now()),
	(uuid(), '1846', '1846', '2', now(), now()),
	(uuid(), '815', '815', '2', now(), now()),
	(uuid(), '1835', '1835', '2', now(), now()),
	(uuid(), '4150', '4150', '2', now(), now()),
	(uuid(), '450 S', '450 S', '2', now(), now()),
	(uuid(), '1840', '1840', '2', now(), now()),
	(uuid(), '2041', '2041', '2', now(), now()),
	(uuid(), '3346', '3346', '2', now(), now()),
	(uuid(), '1843', '1843', '2', now(), now()),
	(uuid(), '1944', '1944', '2', now(), now()),
	(uuid(), '1829', '1829', '2', now(), now()),
	(uuid(), 'CLS 500', 'CLS 500', '2', now(), now()),
	(uuid(), '2048', '2048', '2', now(), now()),
	(uuid(), '2841', '2841', '2', now(), now()),
	(uuid(), '1848', '1848', '2', now(), now()),
	(uuid(), '1218', '1218', '2', now(), now()),
	(uuid(), 'GLE 450', 'GLE 450', '2', now(), now()),
	(uuid(), 'E 250', 'E 250', '2', now(), now()),
	(uuid(), 'C 450', 'C 450', '2', now(), now()),
	(uuid(), '1833', '1833', '2', now(), now()),
	(uuid(), 'G 500', 'G 500', '2', now(), now()),
	(uuid(), 'S 600', 'S 600', '2', now(), now()),
	(uuid(), '2534', '2534', '2', now(), now()),
	(uuid(), 'GLE 63', 'GLE 63', '2', now(), now()),
	(uuid(), '2543', '2543', '2', now(), now()),
	(uuid(), 'S350', 'S350', '2', now(), now()),
	(uuid(), 'GLC300', 'GLC300', '2', now(), now()),
	(uuid(), 'S 560', 'S 560', '2', now(), now()),
	(uuid(), '4041', '4041', '2', now(), now()),
	(uuid(), 'GLE 43', 'GLE 43', '2', now(), now()),
	(uuid(), '3351', '3351', '2', now(), now()),
	(uuid(), '1845', '1845', '2', now(), now()),
	(uuid(), '824', '824', '2', now(), now()),
	(uuid(), '824.', '824.', '2', now(), now()),
	(uuid(), '818', '818', '2', now(), now()),
	(uuid(), '3234', '3234', '2', now(), now()),
	(uuid(), '2545', '2545', '2', now(), now()),
	(uuid(), 'AVANT GARDE', 'AVANT GARDE', '2', now(), now()),
	(uuid(), 'E 320', 'E 320', '2', now(), now()),
	(uuid(), 'TRAVEGO', 'TRAVEGO', '2', now(), now()),
	(uuid(), '3340', '3340', '2', now(), now()),
	(uuid(), 'G 55', 'G 55', '2', now(), now()),
	(uuid(), '1842', '1842', '2', now(), now()),
	(uuid(), '2649', '2649', '2', now(), now()),
	(uuid(), '4040', '4040', '2', now(), now()),
	(uuid(), 'E 400', 'E 400', '2', now(), now()),
	(uuid(), '2648', '2648', '2', now(), now()),
	(uuid(), 'VITO', 'VITO', '2', now(), now()),
	(uuid(), '2144', '2144', '2', now(), now()),
	(uuid(), '2542', '2542', '2', now(), now()),
	(uuid(), '750 I', '750 I', '2', now(), now()),
	(uuid(), '1942', '1942', '2', now(), now()),
	(uuid(), 'C 200', 'C 200', '2', now(), now()),
	(uuid(), 'C43', 'C43', '2', now(), now()),
	(uuid(), 'GLE 350', 'GLE 350', '2', now(), now()),
	(uuid(), 'GL 450', 'GL 450', '2', now(), now()),
	(uuid(), '1951', '1951', '2', now(), now()),
	(uuid(), '1945', '1945', '2', now(), now()),
	(uuid(), 'CLS 53', 'CLS 53', '2', now(), now()),
	(uuid(), 'SETRA', 'SETRA', '2', now(), now()),
	(uuid(), 'CLA 180', 'CLA 180', '2', now(), now()),
	(uuid(), '3848', '3848', '2', now(), now()),
	(uuid(), 'G 63', 'G 63', '2', now(), now()),
	(uuid(), 'CLS 450', 'CLS 450', '2', now(), now()),
	(uuid(), 'GLA 250', 'GLA 250', '2', now(), now()),
	(uuid(), '2655', '2655', '2', now(), now()),
	(uuid(), '822', '822', '2', now(), now()),
	(uuid(), '2533', '2533', '2', now(), now()),
	(uuid(), 'ML 250', 'ML 250', '2', now(), now()),
	(uuid(), '1851', '1851', '2', now(), now()),
	(uuid(), '1943', '1943', '2', now(), now()),
	(uuid(), 'E 63', 'E 63', '2', now(), now()),
	(uuid(), 'GT 43', 'GT 43', '2', now(), now()),
	(uuid(), 'S 350', 'S 350', '2', now(), now()),
	(uuid(), 'CLA 250', 'CLA 250', '2', now(), now()),
	(uuid(), '525 I', '525 I', '2', now(), now()),
	(uuid(), '1940', '1940', '2', now(), now()),
	(uuid(), 'S 450', 'S 450', '2', now(), now()),
	(uuid(), 'CLS 55', 'CLS 55', '2', now(), now()),
	(uuid(), 'E 53', 'E 53', '2', now(), now()),
	(uuid(), '2040', '2040', '2', now(), now()),
	(uuid(), 'E 43', 'E 43', '2', now(), now()),
	(uuid(), 'GLA 180', 'GLA 180', '2', now(), now()),
	(uuid(), 'CLS 350', 'CLS 350', '2', now(), now()),
	(uuid(), '4142', '4142', '2', now(), now()),
	(uuid(), 'GT 2', 'GT 2', '2', now(), now()),
	(uuid(), 'GLC 200', 'GLC 200', '2', now(), now()),
	(uuid(), '3232', '3232', '2', now(), now()),
	(uuid(), '1941', '1941', '2', now(), now()),
	(uuid(), 'X250 D', 'X250 D', '2', now(), now()),
	(uuid(), '2646', '2646', '2', now(), now()),
	(uuid(), 'E 450', 'E 450', '2', now(), now()),
	(uuid(), '2633', '2633', '2', now(), now()),
	(uuid(), '3541', '3541', '2', now(), now()),
	(uuid(), 'CLA 45', 'CLA 45', '2', now(), now()),
	(uuid(), 'X 350 D', 'X 350 D', '2', now(), now()),
	(uuid(), '3844', '3844', '2', now(), now()),
	(uuid(), '2732', '2732', '2', now(), now()),
	(uuid(), '2748', '2748', '2', now(), now()),
	(uuid(), 'C 63', 'C 63', '2', now(), now()),
	(uuid(), 'A 35', 'A 35', '2', now(), now()),
	(uuid(), '3448', '3448', '2', now(), now()),
	(uuid(), 'A 220', 'A 220', '2', now(), now()),
	(uuid(), 'GLC 350', 'GLC 350', '2', now(), now()),
	(uuid(), '2046', '2046', '2', now(), now()),
	(uuid(), '3355', '3355', '2', now(), now()),
	(uuid(), '2551', '2551', '2', now(), now()),
	(uuid(), '2524', '2524', '2', now(), now()),
	(uuid(), '1854', '1854', '2', now(), now()),
	(uuid(), 'A 180', 'A 180', '2', now(), now()),
	(uuid(), 'GLS 450', 'GLS 450', '2', now(), now()),
	(uuid(), 'CLA 220', 'CLA 220', '2', now(), now()),
	(uuid(), '4160', '4160', '2', now(), now()),
	(uuid(), '3348', '3348', '2', now(), now()),
	(uuid(), '3841', '3841', '2', now(), now()),
	(uuid(), 'GLE 53', 'GLE 53', '2', now(), now()),
	(uuid(), 'A 200', 'A 200', '2', now(), now()),
	(uuid(), 'GLC 43', 'GLC 43', '2', now(), now()),
	(uuid(), '3246', '3246', '2', now(), now()),
	(uuid(), '817', '817', '2', now(), now()),
	(uuid(), 'CLA 35', 'CLA 35', '2', now(), now()),
	(uuid(), '4140', '4140', '2', now(), now()),
	(uuid(), 'GLB 250', 'GLB 250', '2', now(), now()),
	(uuid(), 'METRIS', 'METRIS', '2', now(), now()),
	(uuid(), 'GLB 200', 'GLB 200', '2', now(), now()),
	(uuid(), '4448', '4448', '2', now(), now()),
	(uuid(), '2145', '2145', '2', now(), now()),
	(uuid(), '4163', '4163', '2', now(), now()),
	(uuid(), '2526', '2526', '2', now(), now()),
	(uuid(), '3745', '3745', '2', now(), now()),
	(uuid(), '2836', '2836', '2', now(), now()),
	(uuid(), 'AMG GT', 'AMG GT', '2', now(), now()),
	(uuid(), '2745', '2745', '2', now(), now()),
	(uuid(), 'C200 D', 'C200 D', '2', now(), now()),
	(uuid(), '2744', '2744', '2', now(), now()),
	(uuid(), '1860', '1860', '2', now(), now()),
	(uuid(), '1856', '1856', '2', now(), now()),
	(uuid(), '2631', '2631', '2', now(), now()),
	(uuid(), 'GLC 250', 'GLC 250', '2', now(), now()),
	(uuid(), 'GLS 580', 'GLS 580', '2', now(), now()),
	(uuid(), '1890', '1890', '2', now(), now()),
	(uuid(), '3240', '3240', '2', now(), now()),
	(uuid(), '3336', '3336', '2', now(), now()),
	(uuid(), '2844', '2844', '2', now(), now()),
	(uuid(), '2540', '2540', '2', now(), now()),
	(uuid(), '2651', '2651', '2', now(), now()),
	(uuid(), 'CLS 400', 'CLS 400', '2', now(), now()),
	(uuid(), '1936', '1936', '2', now(), now()),
	(uuid(), '1946', '1946', '2', now(), now()),
	(uuid(), '2736', '2736', '2', now(), now()),
	(uuid(), '2043', '2043', '2', now(), now()),
	(uuid(), 'GLA 200', 'GLA 200', '2', now(), now()),
	(uuid(), 'MAYBACH S 600', 'MAYBACH S 600', '2', now(), now()),
	(uuid(), 'C 63 S', 'C 63 S', '2', now(), now()),
	(uuid(), 'V 250', 'V 250', '2', now(), now()),
	(uuid(), 'C 250 D', 'C 250 D', '2', now(), now()),
	(uuid(), 'TOURISMO', 'TOURISMO', '2', now(), now()),
	(uuid(), 'MOTOR,HOME', 'MOTOR,HOME', '2', now(), now()),
	(uuid(), '2555', '2555', '2', now(), now()),
	(uuid(), '1855', '1855', '2', now(), now()),
	(uuid(), 'GL 350', 'GL 350', '2', now(), now()),
	(uuid(), '5244', '5244', '2', now(), now()),
	(uuid(), '1948', '1948', '2', now(), now()),
	(uuid(), '3251', '3251', '2', now(), now()),
	(uuid(), '2240', '2240', '2', now(), now()),
	(uuid(), '3263', '3263', '2', now(), now()),
	(uuid(), '2642', '2642', '2', now(), now()),
	(uuid(), 'B 200 D', 'B 200 D', '2', now(), now()),
	(uuid(), '4061', '4061', '2', now(), now()),
	(uuid(), '2643', '2643', '2', now(), now()),
	(uuid(), '2741', '2741', '2', now(), now()),
	(uuid(), 'GT 53', 'GT 53', '2', now(), now()),
	(uuid(), 'GT 63S', 'GT 63S', '2', now(), now()),
	(uuid(), '2142', '2142', '2', now(), now()),
	(uuid(), '3243', '3243', '2', now(), now()),
	(uuid(), '2051', '2051', '2', now(), now()),
	(uuid(), '3558', '3558', '2', now(), now()),
	(uuid(), '2146', '2146', '2', now(), now()),
	(uuid(), '1955', '1955', '2', now(), now()),
	(uuid(), '2746', '2746', '2', now(), now()),
	(uuid(), '1853', '1853', '2', now(), now()),
	(uuid(), '2560', '2560', '2', now(), now()),
	(uuid(), '3242', '3242', '2', now(), now()),
	(uuid(), '816', '816', '2', now(), now()),
	(uuid(), 'S 580', 'S 580', '2', now(), now()),
	(uuid(), 'E 63 S', 'E 63 S', '2', now(), now()),
	(uuid(), 'B 180', 'B 180', '2', now(), now()),
	(uuid(), 'GLC 300', 'GLC 300', '2', now(), now()),
	(uuid(), 'GLA 35', 'GLA 35', '2', now(), now()),
	(uuid(), 'CLC200', 'CLC200', '2', now(), now()),
	(uuid(), 'E220', 'E220', '2', now(), now()),
	(uuid(), 'E 220', 'E 220', '2', now(), now()),
	(uuid(), '2843', '2843', '2', now(), now()),
	(uuid(), '3540', '3540', '2', now(), now()),
	(uuid(), 'SL 63 AMG', 'SL 63 AMG', '2', now(), now()),
	(uuid(), 'GLE 350 D', 'GLE 350 D', '2', now(), now()),
	(uuid(), 'AMG E 43', 'AMG E 43', '2', now(), now()),
	(uuid(), 'AMG A 35', 'AMG A 35', '2', now(), now()),
	(uuid(), 'AMG GLE 43', 'AMG GLE 43', '2', now(), now()),
	(uuid(), '4840', '4840', '2', now(), now()),
	(uuid(), 'GLA 200D', 'GLA 200D', '2', now(), now()),
	(uuid(), 'AMG G 63', 'AMG G 63', '2', now(), now()),
	(uuid(), 'AMG GT 43', 'AMG GT 43', '2', now(), now()),
	(uuid(), '2653', '2653', '2', now(), now()),
	(uuid(), 'AMG GLC 43', 'AMG GLC 43', '2', now(), now()),
	(uuid(), 'A15', 'A15', '3', now(), now()),
	(uuid(), 'A5', 'A5', '3', now(), now()),
	(uuid(), 'E5', 'E5', '3', now(), now()),
	(uuid(), 'E8', 'E8', '3', now(), now()),
	(uuid(), 'H5', 'H5', '3', now(), now()),
	(uuid(), 'H5TIGGO', 'H5TIGGO', '3', now(), now()),
	(uuid(), 'TIGGO 5', 'TIGGO 5', '3', now(), now()),
	(uuid(), 'X1', 'X1', '3', now(), now()),
	(uuid(), 'X5', 'X5', '3', now(), now()),
	(uuid(), 'S22L', 'S22L', '3', now(), now()),
	(uuid(), 'Q22L', 'Q22L', '3', now(), now()),
	(uuid(), 'Q22B', 'Q22B', '3', now(), now()),
	(uuid(), 'Q22', 'Q22', '3', now(), now()),
	(uuid(), 'Tiggo FL', 'Tiggo FL', '3', now(), now()),
	(uuid(), 'Arrizo7', 'Arrizo7', '3', now(), now()),
	(uuid(), 'A3', 'A3', '3', now(), now()),
	(uuid(), 'A3 HB', 'A3 HB', '3', now(), now()),
	(uuid(), 'E3', 'E3', '3', now(), now()),
	(uuid(), 'Fulwin2 FL', 'Fulwin2 FL', '3', now(), now()),
	(uuid(), 'Fulwin2 FL HB', 'Fulwin2 FL HB', '3', now(), now()),
	(uuid(), 'Fulwin2', 'Fulwin2', '3', now(), now()),
	(uuid(), 'Fulwin2 HB', 'Fulwin2 HB', '3', now(), now()),
	(uuid(), 'A1', 'A1', '3', now(), now()),
	(uuid(), 'New QQ', 'New QQ', '3', now(), now()),
	(uuid(), 'QQ3', 'QQ3', '3', now(), now()),
	(uuid(), 'TIGG07', 'TIGG07', '3', now(), now()),
	(uuid(), 'ARNAGE', 'ARNAGE', '4', now(), now()),
	(uuid(), 'AZURE', 'AZURE', '4', now(), now()),
	(uuid(), 'BENTAYGA', 'BENTAYGA', '4', now(), now()),
	(uuid(), 'CONTINENTAL GT', 'CONTINENTAL GT', '4', now(), now()),
	(uuid(), 'CONTINENTAL GTC', 'CONTINENTAL GTC', '4', now(), now()),
	(uuid(), 'FYING SPUR', 'FYING SPUR', '4', now(), now()),
	(uuid(), 'MULSANNE', 'MULSANNE', '4', now(), now()),
	(uuid(), 'TURBO RT', 'TURBO RT', '4', now(), now()),
	(uuid(), 'Blower', 'Blower', '4', now(), now()),
	(uuid(), 'Arnage RL', 'Arnage RL', '4', now(), now()),
	(uuid(), 'Arnage T', 'Arnage T', '4', now(), now()),
	(uuid(), 'Arnage R', 'Arnage R', '4', now(), now()),
	(uuid(), 'Blue Train', 'Blue Train', '4', now(), now()),
	(uuid(), 'Continental Supersports', 'Continental Supersports', '4', now(), now()),
	(uuid(), 'Continental GT3-R', 'Continental GT3-R', '4', now(), now()),
	(uuid(), 'DB9', 'DB9', '5', now(), now()),
	(uuid(), 'DB9 VOLANTE', 'DB9 VOLANTE', '5', now(), now()),
	(uuid(), 'RAPIDE S', 'RAPIDE S', '5', now(), now()),
	(uuid(), 'VANQUISH', 'VANQUISH', '5', now(), now()),
	(uuid(), 'ANQUISH VOLANTE', 'ANQUISH VOLANTE', '5', now(), now()),
	(uuid(), 'VVANTAGE', 'VVANTAGE', '5', now(), now()),
	(uuid(), 'VANTAGE ROADSTER', 'VANTAGE ROADSTER', '5', now(), now()),
	(uuid(), 'V12 ZAGATO', 'V12 ZAGATO', '5', now(), now()),
	(uuid(), 'VIRAGE', 'VIRAGE', '5', now(), now()),
	(uuid(), 'ONE 77', 'ONE 77', '5', now(), now()),
	(uuid(), 'CYGNET', 'CYGNET', '5', now(), now()),
	(uuid(), 'CC100', 'CC100', '5', now(), now()),
	(uuid(), 'DBS VOLANTE', 'DBS VOLANTE', '5', now(), now()),
	(uuid(), 'DBS COUPE', 'DBS COUPE', '5', now(), now()),
	(uuid(), 'DBX', 'DBX', '5', now(), now()),
	(uuid(), 'A9', 'A9', '6', now(), now()),
	(uuid(), 'FRV', 'FRV', '6', now(), now()),
	(uuid(), 'FRV CROSS', 'FRV CROSS', '6', now(), now()),
	(uuid(), 'FSV', 'FSV', '6', now(), now()),
	(uuid(), 'GALENA', 'GALENA', '6', now(), now()),
	(uuid(), 'H230', 'H230', '6', now(), now()),
	(uuid(), 'H320', 'H320', '6', now(), now()),
	(uuid(), 'H530', 'H530', '6', now(), now()),
	(uuid(), 'S30', 'S30', '6', now(), now()),
	(uuid(), 'SPLENDOR', 'SPLENDOR', '6', now(), now()),
	(uuid(), 'V5', 'V5', '6', now(), now()),
	(uuid(), 'F0', 'F0', '7', now(), now()),
	(uuid(), 'F3', 'F3', '7', now(), now()),
	(uuid(), 'F3R', 'F3R', '7', now(), now()),
	(uuid(), 'FLYER', 'FLYER', '7', now(), now()),
	(uuid(), 'G3', 'G3', '7', now(), now()),
	(uuid(), 'A1', 'A1', '8', now(), now()),
	(uuid(), 'A4', 'A4', '8', now(), now()),
	(uuid(), 'A5', 'A5', '8', now(), now()),
	(uuid(), 'A6', 'A6', '8', now(), now()),
	(uuid(), 'A7', 'A7', '8', now(), now()),
	(uuid(), 'A8', 'A8', '8', now(), now()),
	(uuid(), 'TT', 'TT', '8', now(), now()),
	(uuid(), 'Q3', 'Q3', '8', now(), now()),
	(uuid(), 'Q5', 'Q5', '8', now(), now()),
	(uuid(), 'Q7', 'Q7', '8', now(), now()),
	(uuid(), 'R8', 'R8', '8', now(), now()),
	(uuid(), '100', '100', '8', now(), now()),
	(uuid(), '200', '200', '8', now(), now()),
	(uuid(), '4000', '4000', '8', now(), now()),
	(uuid(), '5000', '5000', '8', now(), now()),
	(uuid(), '80', '80', '8', now(), now()),
	(uuid(), '90', '90', '8', now(), now()),
	(uuid(), 'A3', 'A3', '8', now(), now()),
	(uuid(), 'CABRIOLET', 'CABRIOLET', '8', now(), now()),
	(uuid(), 'Q8', 'Q8', '8', now(), now()),
	(uuid(), 'RS 6', 'RS 6', '8', now(), now()),
	(uuid(), 'RS Q3', 'RS Q3', '8', now(), now()),
	(uuid(), 'S.3', 'S.3', '8', now(), now()),
	(uuid(), 'CAPRI', 'CAPRI', '9', now(), now()),
	(uuid(), 'COUGAR', 'COUGAR', '9', now(), now()),
	(uuid(), 'GRAND MARQUIS', 'GRAND MARQUIS', '9', now(), now()),
	(uuid(), 'LN7', 'LN7', '9', now(), now()),
	(uuid(), 'LYNX', 'LYNX', '9', now(), now()),
	(uuid(), 'MARAUDER', 'MARAUDER', '9', now(), now()),
	(uuid(), 'MARINER', 'MARINER', '9', now(), now()),
	(uuid(), 'MARQUIS', 'MARQUIS', '9', now(), now()),
	(uuid(), 'MILLAN', 'MILLAN', '9', now(), now()),
	(uuid(), 'MONTEGO', 'MONTEGO', '9', now(), now()),
	(uuid(), 'MONTEREY', 'MONTEREY', '9', now(), now()),
	(uuid(), 'MOUNTAINEER', 'MOUNTAINEER', '9', now(), now()),
	(uuid(), 'MYSTIQUE', 'MYSTIQUE', '9', now(), now()),
	(uuid(), 'SABLE', 'SABLE', '9', now(), now()),
	(uuid(), 'TOPAS', 'TOPAS', '9', now(), now()),
	(uuid(), 'TRACER', 'TRACER', '9', now(), now()),
	(uuid(), 'VILLAGER', 'VILLAGER', '9', now(), now()),
	(uuid(), 'ZEPHYR', 'ZEPHYR', '9', now(), now()),
	(uuid(), 'Ghibli S Q4', 'Ghibli S Q4', '10', now(), now()),
	(uuid(), 'GranTurismo Sport', 'GranTurismo Sport', '10', now(), now()),
	(uuid(), 'Quattroporte S', 'Quattroporte S', '10', now(), now()),
	(uuid(), 'GranCabrio', 'GranCabrio', '10', now(), now()),
	(uuid(), 'Ghibli', 'Ghibli', '10', now(), now()),
	(uuid(), 'GranCabrio MC Centennial', 'GranCabrio MC Centennial', '10', now(), now()),
	(uuid(), 'GranTurismo MC Stradale', 'GranTurismo MC Stradale', '10', now(), now()),
	(uuid(), 'Quattroporte S Q4', 'Quattroporte S Q4', '10', now(), now()),
	(uuid(), 'GranTurismo MC Centennial', 'GranTurismo MC Centennial', '10', now(), now()),
	(uuid(), 'GranCabrio Sport', 'GranCabrio Sport', '10', now(), now()),
	(uuid(), 'GranCabrio MC', 'GranCabrio MC', '10', now(), now()),
	(uuid(), 'GranTurismo', 'GranTurismo', '10', now(), now()),
	(uuid(), 'Quattroporte GTS', 'Quattroporte GTS', '10', now(), now()),
	(uuid(), 'SPYDER', 'SPYDER', '10', now(), now()),
	(uuid(), 'COUPE', 'COUPE', '10', now(), now()),
	(uuid(), 'LEVANTE', 'LEVANTE', '10', now(), now()),
	(uuid(), 'BENNI', 'BENNI', '11', now(), now()),
	(uuid(), 'CS 35', 'CS 35', '11', now(), now()),
	(uuid(), 'CS 75', 'CS 75', '11', now(), now()),
	(uuid(), 'CX 20', 'CX 20', '11', now(), now()),
	(uuid(), 'CX 30', 'CX 30', '11', now(), now()),
	(uuid(), 'EADO', 'EADO', '11', now(), now()),
	(uuid(), 'Integra', 'Integra', '12', now(), now()),
	(uuid(), 'NSX', 'NSX', '12', now(), now()),
	(uuid(), 'TL', 'TL', '12', now(), now()),
	(uuid(), 'Vigor', 'Vigor', '12', now(), now()),
	(uuid(), 'RDX', 'RDX', '12', now(), now()),
	(uuid(), 'Legend', 'Legend', '12', now(), now()),
	(uuid(), 'CL', 'CL', '12', now(), now()),
	(uuid(), 'ILX', 'ILX', '12', now(), now()),
	(uuid(), 'MDX', 'MDX', '12', now(), now()),
	(uuid(), 'RL', 'RL', '12', now(), now()),
	(uuid(), 'RLX', 'RLX', '12', now(), now()),
	(uuid(), 'SLX', 'SLX', '12', now(), now()),
	(uuid(), 'ZDX', 'ZDX', '12', now(), now()),
	(uuid(), 'YARIS', 'YARIS', '12', now(), now()),
	(uuid(), 'MURANO', 'MURANO', '12', now(), now()),
	(uuid(), 'E12', 'E12', '12', now(), now()),
	(uuid(), '540', '540', '12', now(), now()),
	(uuid(), '670', '670', '12', now(), now()),
	(uuid(), '325', '325', '12', now(), now()),
	(uuid(), 'TJ00014', 'TJ00014', '12', now(), now()),
	(uuid(), 'GLK 350', 'GLK 350', '12', now(), now()),
	(uuid(), 'E1', 'E1', '12', now(), now()),
	(uuid(), 'L/BUS', 'L/BUS', '12', now(), now()),
	(uuid(), 'X6 M50I', 'X6 M50I', '12', now(), now()),
	(uuid(), 'S-600', 'S-600', '12', now(), now()),
	(uuid(), 'X7 40I', 'X7 40I', '12', now(), now()),
	(uuid(), '10 hp', '10 hp', '13', now(), now()),
	(uuid(), '15 hp', '15 hp', '13', now(), now()),
	(uuid(), '25/30', '25/30', '13', now(), now()),
	(uuid(), '25/30Phantom I', '25/30Phantom I', '13', now(), now()),
	(uuid(), 'Phantom II', 'Phantom II', '13', now(), now()),
	(uuid(), 'Phantom III', 'Phantom III', '13', now(), now()),
	(uuid(), 'Phantom V', 'Phantom V', '13', now(), now()),
	(uuid(), 'Phantom VI', 'Phantom VI', '13', now(), now()),
	(uuid(), 'Silver Cloud', 'Silver Cloud', '13', now(), now()),
	(uuid(), 'Silver Dawn', 'Silver Dawn', '13', now(), now()),
	(uuid(), 'Silver Seraph', 'Silver Seraph', '13', now(), now()),
	(uuid(), 'Silver Shadow', 'Silver Shadow', '13', now(), now()),
	(uuid(), 'Silver Spirit', 'Silver Spirit', '13', now(), now()),
	(uuid(), 'Silver Wraith', 'Silver Wraith', '13', now(), now()),
	(uuid(), 'Twenty', 'Twenty', '13', now(), now()),
	(uuid(), 'Wraith', 'Wraith', '13', now(), now()),
	(uuid(), 'V-8', 'V-8', '13', now(), now()),
	(uuid(), 'CORNICHE', 'CORNICHE', '13', now(), now()),
	(uuid(), 'GHOST', 'GHOST', '13', now(), now()),
	(uuid(), 'PARK WARD', 'PARK WARD', '13', now(), now()),
	(uuid(), 'Beetle', 'Beetle', '14', now(), now()),
	(uuid(), 'Golf', 'Golf', '14', now(), now()),
	(uuid(), 'Touran', 'Touran', '14', now(), now()),
	(uuid(), 'Santana', 'Santana', '14', now(), now()),
	(uuid(), 'Lavida', 'Lavida', '14', now(), now()),
	(uuid(), 'POLO', 'POLO', '14', now(), now()),
	(uuid(), 'Sharan', 'Sharan', '14', now(), now()),
	(uuid(), 'PASSAT', 'PASSAT', '14', now(), now()),
	(uuid(), 'K70', 'K70', '14', now(), now()),
	(uuid(), 'CABRIO', 'CABRIO', '14', now(), now()),
	(uuid(), 'CABRIOLET', 'CABRIOLET', '14', now(), now()),
	(uuid(), 'CC', 'CC', '14', now(), now()),
	(uuid(), 'CORRADO', 'CORRADO', '14', now(), now()),
	(uuid(), 'DASHER', 'DASHER', '14', now(), now()),
	(uuid(), 'E-GOLF', 'E-GOLF', '14', now(), now()),
	(uuid(), 'E-OS', 'E-OS', '14', now(), now()),
	(uuid(), 'EURO VAN', 'EURO VAN', '14', now(), now()),
	(uuid(), 'FOX', 'FOX', '14', now(), now()),
	(uuid(), 'GLI', 'GLI', '14', now(), now()),
	(uuid(), 'JETTA', 'JETTA', '14', now(), now()),
	(uuid(), 'PHAETON', 'PHAETON', '14', now(), now()),
	(uuid(), 'QUANTUM', 'QUANTUM', '14', now(), now()),
	(uuid(), 'R32', 'R32', '14', now(), now()),
	(uuid(), 'TIGUAN', 'TIGUAN', '14', now(), now()),
	(uuid(), 'BETTLE', 'BETTLE', '14', now(), now()),
	(uuid(), 'TOUAREG', 'TOUAREG', '14', now(), now()),
	(uuid(), 'CC SPORT', 'CC SPORT', '14', now(), now()),
	(uuid(), 'SCIROCCO', 'SCIROCCO', '14', now(), now()),
	(uuid(), 'T-ROC', 'T-ROC', '14', now(), now()),
	(uuid(), 'TERAMONT', 'TERAMONT', '14', now(), now()),
	(uuid(), 'Aria', 'Aria', '15', now(), now()),
	(uuid(), 'Bolt', 'Bolt', '15', now(), now()),
	(uuid(), 'Indica', 'Indica', '15', now(), now()),
	(uuid(), 'Indigo', 'Indigo', '15', now(), now()),
	(uuid(), 'Manza', 'Manza', '15', now(), now()),
	(uuid(), 'Movus', 'Movus', '15', now(), now()),
	(uuid(), 'Nano', 'Nano', '15', now(), now()),
	(uuid(), 'Safari Dicor', 'Safari Dicor', '15', now(), now()),
	(uuid(), 'Safari Storme', 'Safari Storme', '15', now(), now()),
	(uuid(), 'Sumo Gold', 'Sumo Gold', '15', now(), now()),
	(uuid(), 'Sumo Grande', 'Sumo Grande', '15', now(), now()),
	(uuid(), 'Venture', 'Venture', '15', now(), now()),
	(uuid(), 'Vista', 'Vista', '15', now(), now()),
	(uuid(), 'Xenon XT', 'Xenon XT', '15', now(), now()),
	(uuid(), 'Zest', 'Zest', '15', now(), now()),
	(uuid(), 'Ace', 'Ace', '15', now(), now()),
	(uuid(), 'Ace Zip', 'Ace Zip', '15', now(), now()),
	(uuid(), 'Defence', 'Defence', '15', now(), now()),
	(uuid(), 'Magic', 'Magic', '15', now(), now()),
	(uuid(), 'Magic Iris', 'Magic Iris', '15', now(), now()),
	(uuid(), 'M&HCV', 'M&HCV', '15', now(), now()),
	(uuid(), 'Prima', 'Prima', '15', now(), now()),
	(uuid(), 'Super Ace', 'Super Ace', '15', now(), now()),
	(uuid(), 'Super Ace MINT', 'Super Ace MINT', '15', now(), now()),
	(uuid(), 'Winger Platinum', 'Winger Platinum', '15', now(), now()),
	(uuid(), 'Ultra', 'Ultra', '15', now(), now()),
	(uuid(), 'Winger', 'Winger', '15', now(), now()),
	(uuid(), 'VENTURE', 'VENTURE', '15', now(), now()),
	(uuid(), 'V3TVF', 'V3TVF', '15', now(), now()),
	(uuid(), 'Cayenne', 'Cayenne', '16', now(), now()),
	(uuid(), '911', '911', '16', now(), now()),
	(uuid(), 'Boxster', 'Boxster', '16', now(), now()),
	(uuid(), '912', '912', '16', now(), now()),
	(uuid(), 'Panamera', 'Panamera', '16', now(), now()),
	(uuid(), 'Carrera', 'Carrera', '16', now(), now()),
	(uuid(), 'Cayman', 'Cayman', '16', now(), now()),
	(uuid(), '918 SPYDER', '918 SPYDER', '16', now(), now()),
	(uuid(), '924', '924', '16', now(), now()),
	(uuid(), '928', '928', '16', now(), now()),
	(uuid(), '944', '944', '16', now(), now()),
	(uuid(), 'MACAN', 'MACAN', '16', now(), now()),
	(uuid(), 'PANAMERA', 'PANAMERA', '16', now(), now()),
	(uuid(), 'MACAN S', 'MACAN S', '16', now(), now()),
	(uuid(), 'GT 4', 'GT 4', '16', now(), now()),
	(uuid(), '718 BOXSTER', '718 BOXSTER', '16', now(), now()),
	(uuid(), '718', '718', '16', now(), now()),
	(uuid(), '911 TARGA 4', '911 TARGA 4', '16', now(), now()),
	(uuid(), '718 CAYMAN GTS', '718 CAYMAN GTS', '16', now(), now()),
	(uuid(), 'Megane', 'Megane', '17', now(), now()),
	(uuid(), 'Clio', 'Clio', '17', now(), now()),
	(uuid(), 'Kangoo', 'Kangoo', '17', now(), now()),
	(uuid(), 'Laguna Coupe', 'Laguna Coupe', '17', now(), now()),
	(uuid(), 'Master', 'Master', '17', now(), now()),
	(uuid(), 'Twingo', 'Twingo', '17', now(), now()),
	(uuid(), 'Twizy', 'Twizy', '17', now(), now()),
	(uuid(), 'Symbol', 'Symbol', '17', now(), now()),
	(uuid(), 'Koleos', 'Koleos', '17', now(), now()),
	(uuid(), '181 SERIES', '181 SERIES', '17', now(), now()),
	(uuid(), 'ALLIANCE', 'ALLIANCE', '17', now(), now()),
	(uuid(), 'ENCORE', 'ENCORE', '17', now(), now()),
	(uuid(), 'FUEGO', 'FUEGO', '17', now(), now()),
	(uuid(), 'LE CAR', 'LE CAR', '17', now(), now()),
	(uuid(), 'SPORT WAGON', 'SPORT WAGON', '17', now(), now()),
	(uuid(), 'FLUENCE', 'FLUENCE', '17', now(), now()),
	(uuid(), 'DUSTER', 'DUSTER', '17', now(), now()),
	(uuid(), 'R350', 'R350', '17', now(), now()),
	(uuid(), 'TGX 18.440', 'TGX 18.440', '17', now(), now()),
	(uuid(), 'GT.', 'GT.', '17', now(), now()),
	(uuid(), '460.', '460.', '17', now(), now()),
	(uuid(), '430,', '430,', '17', now(), now()),
	(uuid(), 'TK135', 'TK135', '17', now(), now()),
	(uuid(), 'T 460', 'T 460', '17', now(), now()),
	(uuid(), 'ESPACE', 'ESPACE', '17', now(), now()),
	(uuid(), 'T440', 'T440', '17', now(), now()),
	(uuid(), '600', '600', '18', now(), now()),
	(uuid(), '1400', '1400', '18', now(), now()),
	(uuid(), '850 Sport', '850 Sport', '18', now(), now()),
	(uuid(), '128', '128', '18', now(), now()),
	(uuid(), 'Ronda', 'Ronda', '18', now(), now()),
	(uuid(), 'Ibiza Mk1', 'Ibiza Mk1', '18', now(), now()),
	(uuid(), 'Toledo Mk1', 'Toledo Mk1', '18', now(), now()),
	(uuid(), 'Córdoba SX', 'Córdoba SX', '18', now(), now()),
	(uuid(), 'León Mk1 Cupra R', 'León Mk1 Cupra R', '18', now(), now()),
	(uuid(), '1430', '1430', '18', now(), now()),
	(uuid(), 'Córdoba', 'Córdoba', '18', now(), now()),
	(uuid(), 'León TDI', 'León TDI', '18', now(), now()),
	(uuid(), 'Cupra GT', 'Cupra GT', '18', now(), now()),
	(uuid(), '3DR (Hatchback)', '3DR (Hatchback)', '18', now(), now()),
	(uuid(), '5DR (Hatchback)', '5DR (Hatchback)', '18', now(), now()),
	(uuid(), 'Estate/Wagon', 'Estate/Wagon', '18', now(), now()),
	(uuid(), 'Sports Toure', 'Sports Toure', '18', now(), now()),
	(uuid(), 'IBL Concept', 'IBL Concept', '18', now(), now()),
	(uuid(), 'Tango', 'Tango', '18', now(), now()),
	(uuid(), 'Tribu', 'Tribu', '18', now(), now()),
	(uuid(), '132 Madrid', '132 Madrid', '18', now(), now()),
	(uuid(), '850 Spider vl blue TCE', '850 Spider vl blue TCE', '18', now(), now()),
	(uuid(), '1200 Sport', '1200 Sport', '18', now(), now()),
	(uuid(), 'Brabus Tailor Made', 'Brabus Tailor Made', '19', now(), now()),
	(uuid(), 'City Cabrio', 'City Cabrio', '19', now(), now()),
	(uuid(), 'City Coupe', 'City Coupe', '19', now(), now()),
	(uuid(), 'Forfour', 'Forfour', '19', now(), now()),
	(uuid(), 'FortwoCabrio', 'FortwoCabrio', '19', now(), now()),
	(uuid(), 'Fortwo Cabriolet', 'Fortwo Cabriolet', '19', now(), now()),
	(uuid(), 'Fortwo ED', 'Fortwo ED', '19', now(), now()),
	(uuid(), 'Roadster', 'Roadster', '19', now(), now()),
	(uuid(), 'Crossblade', 'Crossblade', '19', now(), now()),
	(uuid(), 'Smart K', 'Smart K', '19', now(), now()),
	(uuid(), '451 SPORT', '451 SPORT', '19', now(), now()),
	(uuid(), 'PASSION COUPE', 'PASSION COUPE', '19', now(), now()),
	(uuid(), '416', '416', '19', now(), now()),
	(uuid(), '416 SPORT', '416 SPORT', '19', now(), now()),
	(uuid(), '212', '212', '19', now(), now()),
	(uuid(), '451', '451', '19', now(), now()),
	(uuid(), 'FORTWO', 'FORTWO', '19', now(), now()),
	(uuid(), 'C70', 'C70', '20', now(), now()),
	(uuid(), 'C30', 'C30', '20', now(), now()),
	(uuid(), 'S40', 'S40', '20', now(), now()),
	(uuid(), 'V40', 'V40', '20', now(), now()),
	(uuid(), 'S60', 'S60', '20', now(), now()),
	(uuid(), 'XC60', 'XC60', '20', now(), now()),
	(uuid(), 'S80', 'S80', '20', now(), now()),
	(uuid(), 'V70', 'V70', '20', now(), now()),
	(uuid(), 'XC70', 'XC70', '20', now(), now()),
	(uuid(), 'XC90', 'XC90', '20', now(), now()),
	(uuid(), 'S90', 'S90', '20', now(), now()),
	(uuid(), 'V50', 'V50', '20', now(), now()),
	(uuid(), 'ACC', 'ACC', '20', now(), now()),
	(uuid(), 'ACC2', 'ACC2', '20', now(), now()),
	(uuid(), 'Concept You', 'Concept You', '20', now(), now()),
	(uuid(), 'EC', 'EC', '20', now(), now()),
	(uuid(), 'ECC', 'ECC', '20', now(), now()),
	(uuid(), 'ELISABETH', 'ELISABETH', '20', now(), now()),
	(uuid(), 'LCP2000', 'LCP2000', '20', now(), now()),
	(uuid(), 'Margarete Rose', 'Margarete Rose', '20', now(), now()),
	(uuid(), 'PCC', 'PCC', '20', now(), now()),
	(uuid(), 'PCC2', 'PCC2', '20', now(), now()),
	(uuid(), 'Philip', 'Philip', '20', now(), now()),
	(uuid(), 'ReCharge Concept', 'ReCharge Concept', '20', now(), now()),
	(uuid(), 'SCC', 'SCC', '20', now(), now()),
	(uuid(), 'T6', 'T6', '20', now(), now()),
	(uuid(), 'Universe Concep', 'Universe Concep', '20', now(), now()),
	(uuid(), 'VCC', 'VCC', '20', now(), now()),
	(uuid(), 'Venus Bilo', 'Venus Bilo', '20', now(), now()),
	(uuid(), '1800 ESC', '1800 ESC', '20', now(), now()),
	(uuid(), '3CC', '3CC', '20', now(), now()),
	(uuid(), 'C202', 'C202', '20', now(), now()),
	(uuid(), 'P1800', 'P1800', '20', now(), now()),
	(uuid(), 'P1900', 'P1900', '20', now(), now()),
	(uuid(), 'TR670', 'TR670', '20', now(), now()),
	(uuid(), 'Duett', 'Duett', '20', now(), now()),
	(uuid(), 'PV650', 'PV650', '20', now(), now()),
	(uuid(), 'PV444', 'PV444', '20', now(), now()),
	(uuid(), '240', '240', '20', now(), now()),
	(uuid(), '260', '260', '20', now(), now()),
	(uuid(), '740', '740', '20', now(), now()),
	(uuid(), '760', '760', '20', now(), now()),
	(uuid(), '780', '780', '20', now(), now()),
	(uuid(), '850', '850', '20', now(), now()),
	(uuid(), '900', '900', '20', now(), now()),
	(uuid(), '960', '960', '20', now(), now()),
	(uuid(), '940', '940', '20', now(), now()),
	(uuid(), 'C71', 'C71', '20', now(), now()),
	(uuid(), 'COUPE', 'COUPE', '20', now(), now()),
	(uuid(), 'DL', 'DL', '20', now(), now()),
	(uuid(), 'GLE', 'GLE', '20', now(), now()),
	(uuid(), 'GL', 'GL', '20', now(), now()),
	(uuid(), 'V90', 'V90', '20', now(), now()),
	(uuid(), 'V60 CROSS COUNTRY', 'V60 CROSS COUNTRY', '20', now(), now()),
	(uuid(), 'S60 INSCRIPTION', 'S60 INSCRIPTION', '20', now(), now()),
	(uuid(), 'S60 CROSS COUNTRY', 'S60 CROSS COUNTRY', '20', now(), now()),
	(uuid(), 'FH12', 'FH12', '20', now(), now()),
	(uuid(), 'FH-12', 'FH-12', '20', now(), now()),
	(uuid(), 'FH-440', 'FH-440', '20', now(), now()),
	(uuid(), 'FH460', 'FH460', '20', now(), now()),
	(uuid(), 'FH-420', 'FH-420', '20', now(), now()),
	(uuid(), 'FH-480', 'FH-480', '20', now(), now()),
	(uuid(), 'FH-520', 'FH-520', '20', now(), now()),
	(uuid(), 'FH-400', 'FH-400', '20', now(), now()),
	(uuid(), 'FH13', 'FH13', '20', now(), now()),
	(uuid(), 'FH-500', 'FH-500', '20', now(), now()),
	(uuid(), 'FH 13-510', 'FH 13-510', '20', now(), now()),
	(uuid(), 'FH-16', 'FH-16', '20', now(), now()),
	(uuid(), 'FH-460', 'FH-460', '20', now(), now()),
	(uuid(), 'FH-380', 'FH-380', '20', now(), now()),
	(uuid(), 'FH 540', 'FH 540', '20', now(), now()),
	(uuid(), 'FH-600', 'FH-600', '20', now(), now()),
	(uuid(), '330', '330', '20', now(), now()),
	(uuid(), 'FH 410', 'FH 410', '20', now(), now()),
	(uuid(), 'FH-450', 'FH-450', '20', now(), now()),
	(uuid(), 'FL 240', 'FL 240', '20', now(), now()),
	(uuid(), 'FH-540', 'FH-540', '20', now(), now()),
	(uuid(), 'FH-700', 'FH-700', '20', now(), now()),
	(uuid(), 'FH 640', 'FH 640', '20', now(), now()),
	(uuid(), 'FH-640', 'FH-640', '20', now(), now()),
	(uuid(), 'FH-660', 'FH-660', '20', now(), now()),
	(uuid(), 'FH-750', 'FH-750', '20', now(), now()),
	(uuid(), 'TGX 26.500', 'TGX 26.500', '20', now(), now()),
	(uuid(), 'Meriva', 'Meriva', '22', now(), now()),
	(uuid(), 'Astra', 'Astra', '22', now(), now()),
	(uuid(), 'Corsa', 'Corsa', '22', now(), now()),
	(uuid(), 'Zafira', 'Zafira', '22', now(), now()),
	(uuid(), 'Omega', 'Omega', '22', now(), now()),
	(uuid(), 'Calibra', 'Calibra', '22', now(), now()),
	(uuid(), 'Vectra', 'Vectra', '22', now(), now()),
	(uuid(), 'Kadett D', 'Kadett D', '22', now(), now()),
	(uuid(), 'Meriva B', 'Meriva B', '22', now(), now()),
	(uuid(), 'Astra J', 'Astra J', '22', now(), now()),
	(uuid(), 'Corsa D', 'Corsa D', '22', now(), now()),
	(uuid(), 'Zafira A', 'Zafira A', '22', now(), now()),
	(uuid(), 'Astra G', 'Astra G', '22', now(), now()),
	(uuid(), 'Omega B', 'Omega B', '22', now(), now()),
	(uuid(), 'Ascona C', 'Ascona C', '22', now(), now()),
	(uuid(), 'Vectra A', 'Vectra A', '22', now(), now()),
	(uuid(), 'Exelero', 'Exelero', '23', now(), now()),
	(uuid(), 'SW 42', 'SW 42', '23', now(), now()),
	(uuid(), 'SW 38', 'SW 38', '23', now(), now()),
	(uuid(), 'Zeppelin', 'Zeppelin', '23', now(), now()),
	(uuid(), '57', '57', '23', now(), now()),
	(uuid(), '57 S', '57 S', '23', now(), now()),
	(uuid(), '62', '62', '23', now(), now()),
	(uuid(), '62S', '62S', '23', now(), now()),
	(uuid(), '62 Landaulet', '62 Landaulet', '23', now(), now()),
	(uuid(), '62S Zeppelin', '62S Zeppelin', '23', now(), now()),
	(uuid(), 'S,560', 'S,560', '23', now(), now()),
	(uuid(), 'S-560', 'S-560', '23', now(), now()),
	(uuid(), 'S,600', 'S,600', '23', now(), now()),
	(uuid(), 'AVIATOR', 'AVIATOR', '24', now(), now()),
	(uuid(), 'BLACKWOOD', 'BLACKWOOD', '24', now(), now()),
	(uuid(), 'FLEETWOOD', 'FLEETWOOD', '24', now(), now()),
	(uuid(), 'CONTINENTAL', 'CONTINENTAL', '24', now(), now()),
	(uuid(), 'LS', 'LS', '24', now(), now()),
	(uuid(), 'MARK LT', 'MARK LT', '24', now(), now()),
	(uuid(), 'MARK V1', 'MARK V1', '24', now(), now()),
	(uuid(), 'MARK VII', 'MARK VII', '24', now(), now()),
	(uuid(), 'MARK VIII', 'MARK VIII', '24', now(), now()),
	(uuid(), 'MKC', 'MKC', '24', now(), now()),
	(uuid(), 'MKS', 'MKS', '24', now(), now()),
	(uuid(), 'MKT', 'MKT', '24', now(), now()),
	(uuid(), 'MKX', 'MKX', '24', now(), now()),
	(uuid(), 'MKZ', 'MKZ', '24', now(), now()),
	(uuid(), 'NAVIGATOR', 'NAVIGATOR', '24', now(), now()),
	(uuid(), 'TOWN CAR', 'TOWN CAR', '24', now(), now()),
	(uuid(), 'ZEPHYR', 'ZEPHYR', '24', now(), now()),
	(uuid(), '9-2X', '9-2X', '25', now(), now()),
	(uuid(), '9-3', '9-3', '25', now(), now()),
	(uuid(), '9-4X', '9-4X', '25', now(), now()),
	(uuid(), '9-7X', '9-7X', '25', now(), now()),
	(uuid(), '900', '900', '25', now(), now()),
	(uuid(), '9000', '9000', '25', now(), now()),
	(uuid(), '2014 xB', '2014 xB', '26', now(), now()),
	(uuid(), '2006 Scion tC', '2006 Scion tC', '26', now(), now()),
	(uuid(), '2015 FR-s', '2015 FR-s', '26', now(), now()),
	(uuid(), 'Scion Fuse', 'Scion Fuse', '26', now(), now()),
	(uuid(), 'Hako', 'Hako', '26', now(), now()),
	(uuid(), 'IQ', 'IQ', '26', now(), now()),
	(uuid(), 'TC', 'TC', '26', now(), now()),
	(uuid(), 'XA', 'XA', '26', now(), now()),
	(uuid(), 'XB', 'XB', '26', now(), now()),
	(uuid(), 'IA', 'IA', '26', now(), now()),
	(uuid(), 'IM', 'IM', '26', now(), now()),
	(uuid(), 'FR-S', 'FR-S', '26', now(), now()),
	(uuid(), 'XD', 'XD', '26', now(), now()),
	(uuid(), 'Zonda Absolute', 'Zonda Absolute', '27', now(), now()),
	(uuid(), 'Zonda Cinque', 'Zonda Cinque', '27', now(), now()),
	(uuid(), 'ZondaTricolore', 'ZondaTricolore', '27', now(), now()),
	(uuid(), 'Zonda S 7.3', 'Zonda S 7.3', '27', now(), now()),
	(uuid(), 'ZondaRevolucion', 'ZondaRevolucion', '27', now(), now()),
	(uuid(), 'Zonda Roadster F', 'Zonda Roadster F', '27', now(), now()),
	(uuid(), 'Zonda Roadster', 'Zonda Roadster', '27', now(), now()),
	(uuid(), 'Zonda R', 'Zonda R', '27', now(), now()),
	(uuid(), 'Zonda PS', 'Zonda PS', '27', now(), now()),
	(uuid(), 'Zonda GJ', 'Zonda GJ', '27', now(), now()),
	(uuid(), 'Zonda F', 'Zonda F', '27', now(), now()),
	(uuid(), 'Zonda C12', 'Zonda C12', '27', now(), now()),
	(uuid(), 'Zonda Cinque Roadster', 'Zonda Cinque Roadster', '27', now(), now()),
	(uuid(), 'M400', 'M400', '28', now(), now()),
	(uuid(), 'M15', 'M15', '28', now(), now()),
	(uuid(), 'M14 M12 GTO 3R', 'M14 M12 GTO 3R', '28', now(), now()),
	(uuid(), 'm600', 'm600', '28', now(), now()),
	(uuid(), '88', '88', '29', now(), now()),
	(uuid(), '98', '98', '29', now(), now()),
	(uuid(), 'ACHIEVA', 'ACHIEVA', '29', now(), now()),
	(uuid(), 'ALERO', 'ALERO', '29', now(), now()),
	(uuid(), 'AURORA', 'AURORA', '29', now(), now()),
	(uuid(), 'BRAVADA', 'BRAVADA', '29', now(), now()),
	(uuid(), 'CALAIS', 'CALAIS', '29', now(), now()),
	(uuid(), 'CIERA', 'CIERA', '29', now(), now()),
	(uuid(), 'CRUISER', 'CRUISER', '29', now(), now()),
	(uuid(), 'CUTLASS', 'CUTLASS', '29', now(), now()),
	(uuid(), 'DELTA', 'DELTA', '29', now(), now()),
	(uuid(), 'FIRENZA', 'FIRENZA', '29', now(), now()),
	(uuid(), 'INTRIGUE', 'INTRIGUE', '29', now(), now()),
	(uuid(), 'LSS', 'LSS', '29', now(), now()),
	(uuid(), 'OMEGA', 'OMEGA', '29', now(), now()),
	(uuid(), 'REGENCY', 'REGENCY', '29', now(), now()),
	(uuid(), 'SILHOUTLE', 'SILHOUTLE', '29', now(), now()),
	(uuid(), 'TORONADO', 'TORONADO', '29', now(), now()),
	(uuid(), 'TOURING', 'TOURING', '29', now(), now()),
	(uuid(), 'Aero 8', 'Aero 8', '30', now(), now()),
	(uuid(), 'AeroMax', 'AeroMax', '30', now(), now()),
	(uuid(), 'Roadster', 'Roadster', '30', now(), now()),
	(uuid(), 'Eva GT', 'Eva GT', '30', now(), now()),
	(uuid(), 'Runabout', 'Runabout', '30', now(), now()),
	(uuid(), 'Aero Coupe', 'Aero Coupe', '30', now(), now()),
	(uuid(), 'Anniversdary 4/4', 'Anniversdary 4/4', '30', now(), now()),
	(uuid(), 'Plus 4', 'Plus 4', '30', now(), now()),
	(uuid(), 'Lifecar', 'Lifecar', '30', now(), now()),
	(uuid(), 'EV Concept', 'EV Concept', '31', now(), now()),
	(uuid(), 'CS', 'CS', '31', now(), now()),
	(uuid(), 'ICON', 'ICON', '31', now(), now()),
	(uuid(), 'GT', 'GT', '31', now(), now()),
	(uuid(), 'MG5', 'MG5', '31', now(), now()),
	(uuid(), '3Form', '3Form', '31', now(), now()),
	(uuid(), '3Form Sport', '3Form Sport', '31', now(), now()),
	(uuid(), '3Style', '3Style', '31', now(), now()),
	(uuid(), '3Time', '3Time', '31', now(), now()),
	(uuid(), 'MG EX-E', 'MG EX-E', '31', now(), now()),
	(uuid(), 'Metro', 'Metro', '31', now(), now()),
	(uuid(), 'ZR', 'ZR', '31', now(), now()),
	(uuid(), 'F1', 'F1', '32', now(), now()),
	(uuid(), 'MP4/98T', 'MP4/98T', '32', now(), now()),
	(uuid(), 'SLR', 'SLR', '32', now(), now()),
	(uuid(), 'MP4-12C', 'MP4-12C', '32', now(), now()),
	(uuid(), 'P1', 'P1', '32', now(), now()),
	(uuid(), '650S', '650S', '32', now(), now()),
	(uuid(), '675LT', '675LT', '32', now(), now()),
	(uuid(), '540C', '540C', '32', now(), now()),
	(uuid(), '570S', '570S', '32', now(), now()),
	(uuid(), 'M2B', 'M2B', '32', now(), now()),
	(uuid(), 'M7A', 'M7A', '32', now(), now()),
	(uuid(), 'M1A', 'M1A', '32', now(), now()),
	(uuid(), 'M8D', 'M8D', '32', now(), now()),
	(uuid(), 'M16C', 'M16C', '32', now(), now()),
	(uuid(), 'F1 GTR', 'F1 GTR', '32', now(), now()),
	(uuid(), 'GT', 'GT', '32', now(), now()),
	(uuid(), 'ELISE', 'ELISE', '33', now(), now()),
	(uuid(), 'ELISE CLUB RACER', 'ELISE CLUB RACER', '33', now(), now()),
	(uuid(), 'ELISE S', 'ELISE S', '33', now(), now()),
	(uuid(), 'EXIGE S', 'EXIGE S', '33', now(), now()),
	(uuid(), 'EXIGE S ROADSTER', 'EXIGE S ROADSTER', '33', now(), now()),
	(uuid(), 'EVORA', 'EVORA', '33', now(), now()),
	(uuid(), 'EVORA S', 'EVORA S', '33', now(), now()),
	(uuid(), 'EVORA SPORTS RACER', 'EVORA SPORTS RACER', '33', now(), now()),
	(uuid(), '77', '77', '33', now(), now()),
	(uuid(), '99T', '99T', '33', now(), now()),
	(uuid(), '72', '72', '33', now(), now()),
	(uuid(), 'E20', 'E20', '33', now(), now()),
	(uuid(), 'Mk I 1948', 'Mk I 1948', '33', now(), now()),
	(uuid(), 'Mk IX', 'Mk IX', '33', now(), now()),
	(uuid(), 'Eleven', 'Eleven', '33', now(), now()),
	(uuid(), 'Elite', 'Elite', '33', now(), now()),
	(uuid(), '26R', '26R', '33', now(), now()),
	(uuid(), 'Europa', 'Europa', '33', now(), now()),
	(uuid(), 'Esprit V8', 'Esprit V8', '33', now(), now()),
	(uuid(), 'Elise GT1 Road Car', 'Elise GT1 Road Car', '33', now(), now()),
	(uuid(), 'Lotus Esprit', 'Lotus Esprit', '33', now(), now()),
	(uuid(), '1000', '1000', '34', now(), now()),
	(uuid(), '2000 SUNBIRD', '2000 SUNBIRD', '34', now(), now()),
	(uuid(), '6000', '6000', '34', now(), now()),
	(uuid(), 'AZTEK', 'AZTEK', '34', now(), now()),
	(uuid(), 'BONNEVILLE', 'BONNEVILLE', '34', now(), now()),
	(uuid(), 'CATALINA', 'CATALINA', '34', now(), now()),
	(uuid(), 'FIERO', 'FIERO', '34', now(), now()),
	(uuid(), 'FIREBIRD', 'FIREBIRD', '34', now(), now()),
	(uuid(), 'G3', 'G3', '34', now(), now()),
	(uuid(), 'G5', 'G5', '34', now(), now()),
	(uuid(), 'G6', 'G6', '34', now(), now()),
	(uuid(), 'G8', 'G8', '34', now(), now()),
	(uuid(), 'GRAND AM', 'GRAND AM', '34', now(), now()),
	(uuid(), 'GRAND LEMANS', 'GRAND LEMANS', '34', now(), now()),
	(uuid(), 'GRAND PRIX', 'GRAND PRIX', '34', now(), now()),
	(uuid(), 'GTO', 'GTO', '34', now(), now()),
	(uuid(), 'J2000', 'J2000', '34', now(), now()),
	(uuid(), 'LEMANS', 'LEMANS', '34', now(), now()),
	(uuid(), 'MONTANA', 'MONTANA', '34', now(), now()),
	(uuid(), 'PARISIENNE', 'PARISIENNE', '34', now(), now()),
	(uuid(), 'PHOENEX', 'PHOENEX', '34', now(), now()),
	(uuid(), 'SAFARI', 'SAFARI', '34', now(), now()),
	(uuid(), 'SUNFIRE', 'SUNFIRE', '34', now(), now()),
	(uuid(), 'T1000', 'T1000', '34', now(), now()),
	(uuid(), 'TORRENT', 'TORRENT', '34', now(), now()),
	(uuid(), 'TRANS SPORT', 'TRANS SPORT', '34', now(), now()),
	(uuid(), 'VIBE', 'VIBE', '34', now(), now()),
	(uuid(), 'ACCLAIM', 'ACCLAIM', '35', now(), now()),
	(uuid(), 'ARROW', 'ARROW', '35', now(), now()),
	(uuid(), 'BREEZE', 'BREEZE', '35', now(), now()),
	(uuid(), 'CARAVELL', 'CARAVELL', '35', now(), now()),
	(uuid(), 'CHAMP', 'CHAMP', '35', now(), now()),
	(uuid(), 'CONQUEST', 'CONQUEST', '35', now(), now()),
	(uuid(), 'COLT', 'COLT', '35', now(), now()),
	(uuid(), 'GRAN FURY', 'GRAN FURY', '35', now(), now()),
	(uuid(), 'HORIZON', 'HORIZON', '35', now(), now()),
	(uuid(), 'LAZER', 'LAZER', '35', now(), now()),
	(uuid(), 'NEON', 'NEON', '35', now(), now()),
	(uuid(), 'PROWLER', 'PROWLER', '35', now(), now()),
	(uuid(), 'RELIANT', 'RELIANT', '35', now(), now()),
	(uuid(), 'SAPPORO', 'SAPPORO', '35', now(), now()),
	(uuid(), 'SCAMP', 'SCAMP', '35', now(), now()),
	(uuid(), 'SUNDANCE', 'SUNDANCE', '35', now(), now()),
	(uuid(), 'TRAILDUSTER', 'TRAILDUSTER', '35', now(), now()),
	(uuid(), 'TURISMO', 'TURISMO', '35', now(), now()),
	(uuid(), 'VOYAGER', 'VOYAGER', '35', now(), now()),
	(uuid(), '1500', '1500', '36', now(), now()),
	(uuid(), '2500', '2500', '36', now(), now()),
	(uuid(), '4500', '4500', '36', now(), now()),
	(uuid(), '5500', '5500', '36', now(), now()),
	(uuid(), 'CARGO VAN', 'CARGO VAN', '36', now(), now()),
	(uuid(), 'DAKOTA', 'DAKOTA', '36', now(), now()),
	(uuid(), 'PROMASTER', 'PROMASTER', '36', now(), now()),
	(uuid(), 'PROMASTER VAN', 'PROMASTER VAN', '36', now(), now()),
	(uuid(), 'PROMASTER CITY', 'PROMASTER CITY', '36', now(), now()),
	(uuid(), 'PROMASTER WAGON', 'PROMASTER WAGON', '36', now(), now()),
	(uuid(), 'MOTOR-HOME', 'MOTOR-HOME', '36', now(), now()),
	(uuid(), '3500', '3500', '36', now(), now()),
	(uuid(), 'H1', 'H1', '37', now(), now()),
	(uuid(), 'H2', 'H2', '37', now(), now()),
	(uuid(), 'H3', 'H3', '37', now(), now()),
	(uuid(), '200SX', '200SX', '39', now(), now()),
	(uuid(), '210', '210', '39', now(), now()),
	(uuid(), '280ZX', '280ZX', '39', now(), now()),
	(uuid(), '310', '310', '39', now(), now()),
	(uuid(), '510', '510', '39', now(), now()),
	(uuid(), '720', '720', '39', now(), now()),
	(uuid(), '810', '810', '39', now(), now()),
	(uuid(), 'B-210', 'B-210', '39', now(), now()),
	(uuid(), 'MAXIMA', 'MAXIMA', '39', now(), now()),
	(uuid(), 'SENTRA', 'SENTRA', '39', now(), now()),
	(uuid(), 'STANSA', 'STANSA', '39', now(), now()),
	(uuid(), 'BLUEBIRD', 'BLUEBIRD', '39', now(), now()),
	(uuid(), 'GO', 'GO', '39', now(), now()),
	(uuid(), 'A5', 'A5', '40', now(), now()),
	(uuid(), 'MZ 40', 'MZ 40', '40', now(), now()),
	(uuid(), 'A1', 'A1', '40', now(), now()),
	(uuid(), 'H30', 'H30', '41', now(), now()),
	(uuid(), 'S30', 'S30', '41', now(), now()),
	(uuid(), 'LOBO', 'LOBO', '42', now(), now()),
	(uuid(), 'A380', 'A380', '43', now(), now()),
	(uuid(), 'Q22', 'Q22', '44', now(), now()),
	(uuid(), 'TIVOLI', 'TIVOLI', '45', now(), now()),
	(uuid(), 'ACTYON', 'ACTYON', '45', now(), now()),
	(uuid(), 'ACTYON SPORT', 'ACTYON SPORT', '45', now(), now()),
	(uuid(), 'KORANDO', 'KORANDO', '45', now(), now()),
	(uuid(), 'MUSSO', 'MUSSO', '45', now(), now()),
	(uuid(), 'REXTON', 'REXTON', '45', now(), now()),
	(uuid(), 'SUNLONG', 'SUNLONG', '45', now(), now()),
	(uuid(), '5008', '5008', '46', now(), now()),
	(uuid(), 'M300', 'M300', '46', now(), now()),
	(uuid(), 'M300V10', 'M300V10', '46', now(), now()),
	(uuid(), 'XPLOSION', 'XPLOSION', '46', now(), now()),
	(uuid(), 'Z100', 'Z100', '46', now(), now()),
	(uuid(), 'Z200', 'Z200', '46', now(), now()),
	(uuid(), 'Z300', 'Z300', '46', now(), now()),
	(uuid(), 'T700', 'T700', '46', now(), now()),
	(uuid(), 'ASTRA', 'ASTRA', '47', now(), now()),
	(uuid(), 'AURA', 'AURA', '47', now(), now()),
	(uuid(), 'COUPE', 'COUPE', '47', now(), now()),
	(uuid(), 'ION', 'ION', '47', now(), now()),
	(uuid(), 'L-SERIES', 'L-SERIES', '47', now(), now()),
	(uuid(), 'OUTLOOK', 'OUTLOOK', '47', now(), now()),
	(uuid(), 'RELAY', 'RELAY', '47', now(), now()),
	(uuid(), 'S-SERIES', 'S-SERIES', '47', now(), now()),
	(uuid(), 'SKY', 'SKY', '47', now(), now()),
	(uuid(), 'VUE', 'VUE', '47', now(), now()),
	(uuid(), 'MEDALION', 'MEDALION', '48', now(), now()),
	(uuid(), 'PREMIER', 'PREMIER', '48', now(), now()),
	(uuid(), 'SUMMIT', 'SUMMIT', '48', now(), now()),
	(uuid(), 'TALON', 'TALON', '48', now(), now()),
	(uuid(), '1100', '1100', '49', now(), now()),
	(uuid(), '124', '124', '49', now(), now()),
	(uuid(), '125', '125', '49', now(), now()),
	(uuid(), '126', '126', '49', now(), now()),
	(uuid(), '127', '127', '49', now(), now()),
	(uuid(), '128', '128', '49', now(), now()),
	(uuid(), '1300', '1300', '49', now(), now()),
	(uuid(), '131', '131', '49', now(), now()),
	(uuid(), '133', '133', '49', now(), now()),
	(uuid(), '500', '500', '49', now(), now()),
	(uuid(), '500L', '500L', '49', now(), now()),
	(uuid(), 'ALBEA', 'ALBEA', '49', now(), now()),
	(uuid(), 'ARGENTINA', 'ARGENTINA', '49', now(), now()),
	(uuid(), 'BARCHIETTA', 'BARCHIETTA', '49', now(), now()),
	(uuid(), 'BARINA', 'BARINA', '49', now(), now()),
	(uuid(), 'BRAVA', 'BRAVA', '49', now(), now()),
	(uuid(), 'REGATA', 'REGATA', '49', now(), now()),
	(uuid(), 'QUBO', 'QUBO', '49', now(), now()),
	(uuid(), 'PUNTO EVO', 'PUNTO EVO', '49', now(), now()),
	(uuid(), 'POLONEZ', 'POLONEZ', '49', now(), now()),
	(uuid(), 'PETRA', 'PETRA', '49', now(), now()),
	(uuid(), 'PANDA', 'PANDA', '49', now(), now()),
	(uuid(), 'PALIIO', 'PALIIO', '49', now(), now()),
	(uuid(), 'NOVA', 'NOVA', '49', now(), now()),
	(uuid(), 'MAREA', 'MAREA', '49', now(), now()),
	(uuid(), 'LINEA', 'LINEA', '49', now(), now()),
	(uuid(), 'FLORIDA', 'FLORIDA', '49', now(), now()),
	(uuid(), 'FIORINO', 'FIORINO', '49', now(), now()),
	(uuid(), 'DUCADOGANTO', 'DUCADOGANTO', '49', now(), now()),
	(uuid(), 'DOBLO', 'DOBLO', '49', now(), now()),
	(uuid(), 'CROMA', 'CROMA', '49', now(), now()),
	(uuid(), 'BRAVO', 'BRAVO', '49', now(), now()),
	(uuid(), 'RITMO', 'RITMO', '49', now(), now()),
	(uuid(), 'SHAHIN', 'SHAHIN', '49', now(), now()),
	(uuid(), 'SIENA', 'SIENA', '49', now(), now()),
	(uuid(), 'TEMPRA', 'TEMPRA', '49', now(), now()),
	(uuid(), 'TIPO', 'TIPO', '49', now(), now()),
	(uuid(), 'UNO', 'UNO', '49', now(), now()),
	(uuid(), 'EC 18', 'EC 18', '50', now(), now()),
	(uuid(), 'EC 7', 'EC 7', '50', now(), now()),
	(uuid(), 'EC 7 RV', 'EC 7 RV', '50', now(), now()),
	(uuid(), 'EC 8', 'EC 8', '50', now(), now()),
	(uuid(), 'EX 7', 'EX 7', '50', now(), now()),
	(uuid(), 'PANDINO', 'PANDINO', '50', now(), now()),
	(uuid(), 'X PANDINO', 'X PANDINO', '50', now(), now()),
	(uuid(), 'BESTURN', 'BESTURN', '51', now(), now()),
	(uuid(), 'DREAM', 'DREAM', '51', now(), now()),
	(uuid(), 'FREEDOM', 'FREEDOM', '51', now(), now()),
	(uuid(), 'NAUGHTY', 'NAUGHTY', '51', now(), now()),
	(uuid(), 'VITA', 'VITA', '51', now(), now()),
	(uuid(), 'CK', 'CK', '52', now(), now()),
	(uuid(), 'EC7', 'EC7', '52', now(), now()),
	(uuid(), 'EC7 RV', 'EC7 RV', '52', now(), now()),
	(uuid(), 'EC8', 'EC8', '52', now(), now()),
	(uuid(), 'EMGRAND 7', 'EMGRAND 7', '52', now(), now()),
	(uuid(), 'EMGRAND 7 RV', 'EMGRAND 7 RV', '52', now(), now()),
	(uuid(), 'EMGRAND 8', 'EMGRAND 8', '52', now(), now()),
	(uuid(), 'EMGRAND X7', 'EMGRAND X7', '52', now(), now()),
	(uuid(), 'ENGLON', 'ENGLON', '52', now(), now()),
	(uuid(), 'EX7', 'EX7', '52', now(), now()),
	(uuid(), 'FC', 'FC', '52', now(), now()),
	(uuid(), 'FRUITS', 'FRUITS', '52', now(), now()),
	(uuid(), 'GC2', 'GC2', '52', now(), now()),
	(uuid(), 'GC7', 'GC7', '52', now(), now()),
	(uuid(), 'GX2', 'GX2', '52', now(), now()),
	(uuid(), 'LC', 'LC', '52', now(), now()),
	(uuid(), 'LC CROSS', 'LC CROSS', '52', now(), now()),
	(uuid(), 'MAPLE', 'MAPLE', '52', now(), now()),
	(uuid(), 'MK', 'MK', '52', now(), now()),
	(uuid(), 'PANDA', 'PANDA', '52', now(), now()),
	(uuid(), 'PANDINO', 'PANDINO', '52', now(), now()),
	(uuid(), 'SPARKY', 'SPARKY', '52', now(), now()),
	(uuid(), 'X PANDINO', 'X PANDINO', '52', now(), now()),
	(uuid(), 'C30', 'C30', '53', now(), now()),
	(uuid(), 'COOLBEAR', 'COOLBEAR', '53', now(), now()),
	(uuid(), 'DEER', 'DEER', '53', now(), now()),
	(uuid(), 'FLORID', 'FLORID', '53', now(), now()),
	(uuid(), 'HOVER', 'HOVER', '53', now(), now()),
	(uuid(), 'PERI', 'PERI', '53', now(), now()),
	(uuid(), 'GS5', 'GS5', '54', now(), now()),
	(uuid(), 'GA3', 'GA3', '54', now(), now()),
	(uuid(), 'GA5', 'GA5', '54', now(), now()),
	(uuid(), 'VIEW', 'VIEW', '55', now(), now()),
	(uuid(), 'SUP', 'SUP', '55', now(), now()),
	(uuid(), 'TUNLAND', 'TUNLAND', '55', now(), now()),
	(uuid(), 'S5', 'S5', '56', now(), now()),
	(uuid(), 'A 10', 'A 10', '56', now(), now()),
	(uuid(), 'B 15', 'B 15', '56', now(), now()),
	(uuid(), 'J 15', 'J 15', '56', now(), now()),
	(uuid(), 'J2', 'J2', '56', now(), now()),
	(uuid(), 'J3', 'J3', '56', now(), now()),
	(uuid(), 'J5', 'J5', '56', now(), now()),
	(uuid(), 'J6', 'J6', '56', now(), now()),
	(uuid(), 'M5', 'M5', '56', now(), now()),
	(uuid(), 'S1', 'S1', '56', now(), now()),
	(uuid(), 'S3', 'S3', '56', now(), now()),
	(uuid(), 'HFC 1061 K', 'HFC 1061 K', '56', now(), now()),
	(uuid(), 'HFC 3035 K', 'HFC 3035 K', '56', now(), now()),
	(uuid(), 'FOISON', 'FOISON', '57', now(), now()),
	(uuid(), '320', '320', '57', now(), now()),
	(uuid(), '520', '520', '57', now(), now()),
	(uuid(), 'X60', 'X60', '57', now(), now()),
	(uuid(), 'BETA', 'BETA', '58', now(), now()),
	(uuid(), 'DEDRA', 'DEDRA', '58', now(), now()),
	(uuid(), 'DELTA', 'DELTA', '58', now(), now()),
	(uuid(), 'MUSA', 'MUSA', '58', now(), now()),
	(uuid(), 'THEMA', 'THEMA', '58', now(), now()),
	(uuid(), 'RICH', 'RICH', '60', now(), now()),
	(uuid(), 'CRYSTALA', 'CRYSTALA', '61', now(), now()),
	(uuid(), 'VERYCA', 'VERYCA', '61', now(), now()),
	(uuid(), 'V3', 'V3', '61', now(), now()),
	(uuid(), 'V5', 'V5', '61', now(), now()),
	(uuid(), 'V6', 'V6', '61', now(), now()),
	(uuid(), 'TIGGO', 'TIGGO', '62', now(), now()),
	(uuid(), 'A11', 'A11', '62', now(), now()),
	(uuid(), 'A113', 'A113', '62', now(), now()),
	(uuid(), 'A213', 'A213', '62', now(), now()),
	(uuid(), 'A516', 'A516', '62', now(), now()),
	(uuid(), 'A620', 'A620', '62', now(), now()),
	(uuid(), 'CHERY QQ', 'CHERY QQ', '62', now(), now()),
	(uuid(), 'ENVY', 'ENVY', '62', now(), now()),
	(uuid(), 'M11', 'M11', '62', now(), now()),
	(uuid(), 'M12', 'M12', '62', now(), now()),
	(uuid(), 'WIRA', 'WIRA', '65', now(), now()),
	(uuid(), 'GEN 2', 'GEN 2', '65', now(), now()),
	(uuid(), 'GEN 3', 'GEN 3', '65', now(), now()),
	(uuid(), 'PERSONA', 'PERSONA', '65', now(), now()),
	(uuid(), 'SAGA', 'SAGA', '65', now(), now()),
	(uuid(), 'WAJA', 'WAJA', '65', now(), now()),
	(uuid(), 'A1', 'A1', '66', now(), now()),
	(uuid(), '3', '3', '67', now(), now()),
	(uuid(), '350', '350', '67', now(), now()),
	(uuid(), '5', '5', '67', now(), now()),
	(uuid(), '550', '550', '67', now(), now()),
	(uuid(), '6', '6', '67', now(), now()),
	(uuid(), '7', '7', '67', now(), now()),
	(uuid(), '750', '750', '67', now(), now()),
	(uuid(), 'CROSSOVER', 'CROSSOVER', '67', now(), now()),
	(uuid(), 'TF', 'TF', '67', now(), now()),
	(uuid(), 'ZR', 'ZR', '67', now(), now()),
	(uuid(), 'ZS', 'ZS', '67', now(), now()),
	(uuid(), 'ZT', 'ZT', '67', now(), now()),
	(uuid(), 'TAVRIA', 'TAVRIA', '69', now(), now()),
	(uuid(), 'SAMARA', 'SAMARA', '69', now(), now()),
	(uuid(), 'PRIORA', 'PRIORA', '69', now(), now()),
	(uuid(), 'OKA', 'OKA', '69', now(), now()),
	(uuid(), 'KALINA', 'KALINA', '69', now(), now()),
	(uuid(), 'NIVA', 'NIVA', '69', now(), now()),
	(uuid(), 'GRANTA', 'GRANTA', '69', now(), now()),
	(uuid(), 'ALEKO', 'ALEKO', '69', now(), now()),
	(uuid(), '2110', '2110', '69', now(), now()),
	(uuid(), '2107', '2107', '69', now(), now()),
	(uuid(), '2106', '2106', '69', now(), now()),
	(uuid(), '2104', '2104', '69', now(), now()),
	(uuid(), '2103', '2103', '69', now(), now()),
	(uuid(), '2102', '2102', '69', now(), now()),
	(uuid(), '2101', '2101', '69', now(), now()),
	(uuid(), '1500', '1500', '69', now(), now()),
	(uuid(), '124', '124', '69', now(), now()),
	(uuid(), '1200', '1200', '69', now(), now()),
	(uuid(), 'GAZELLE', 'GAZELLE', '71', now(), now()),
	(uuid(), 'BX', 'BX', '72', now(), now()),
	(uuid(), 'C 15', 'C 15', '72', now(), now()),
	(uuid(), 'C ELYSEE', 'C ELYSEE', '72', now(), now()),
	(uuid(), 'C1', 'C1', '72', now(), now()),
	(uuid(), 'C3', 'C3', '72', now(), now()),
	(uuid(), 'C3 PICASSO', 'C3 PICASSO', '72', now(), now()),
	(uuid(), 'C4', 'C4', '72', now(), now()),
	(uuid(), 'C4 GRAND PICASSO', 'C4 GRAND PICASSO', '72', now(), now()),
	(uuid(), 'C4 PICASSO', 'C4 PICASSO', '72', now(), now()),
	(uuid(), 'C5', 'C5', '72', now(), now()),
	(uuid(), 'C6', 'C6', '72', now(), now()),
	(uuid(), 'C8', 'C8', '72', now(), now()),
	(uuid(), 'CX', 'CX', '72', now(), now()),
	(uuid(), 'DS3', 'DS3', '72', now(), now()),
	(uuid(), 'DS4', 'DS4', '72', now(), now()),
	(uuid(), 'DS5', 'DS5', '72', now(), now()),
	(uuid(), 'JUMPER', 'JUMPER', '72', now(), now()),
	(uuid(), 'XANTIA', 'XANTIA', '72', now(), now()),
	(uuid(), 'XSARA', 'XSARA', '72', now(), now()),
	(uuid(), 'ZX', 'ZX', '72', now(), now()),
	(uuid(), 'Traction Avant', 'Traction Avant', '72', now(), now()),
	(uuid(), 'Berlingo', 'Berlingo', '72', now(), now()),
	(uuid(), 'C-Crosser', 'C-Crosser', '72', now(), now()),
	(uuid(), 'C-ZERO', 'C-ZERO', '72', now(), now()),
	(uuid(), 'PICASSO', 'PICASSO', '72', now(), now()),
	(uuid(), 'Z4', 'Z4', '76', now(), now()),
	(uuid(), 'Z3', 'Z3', '76', now(), now()),
	(uuid(), 'Z1', 'Z1', '76', now(), now()),
	(uuid(), 'X2', 'X2', '76', now(), now()),
	(uuid(), 'X3', 'X3', '76', now(), now()),
	(uuid(), 'X4', 'X4', '76', now(), now()),
	(uuid(), 'X6', 'X6', '76', now(), now()),
	(uuid(), 'COUPE I3', 'COUPE I3', '76', now(), now()),
	(uuid(), 'COUPE I8', 'COUPE I8', '76', now(), now()),
	(uuid(), 'M3', 'M3', '76', now(), now()),
	(uuid(), 'M4', 'M4', '76', now(), now()),
	(uuid(), '525', '525', '76', now(), now()),
	(uuid(), '528', '528', '76', now(), now()),
	(uuid(), '530', '530', '76', now(), now()),
	(uuid(), '535', '535', '76', now(), now()),
	(uuid(), '545', '545', '76', now(), now()),
	(uuid(), '628', '628', '76', now(), now()),
	(uuid(), '630', '630', '76', now(), now()),
	(uuid(), '650', '650', '76', now(), now()),
	(uuid(), '633', '633', '76', now(), now()),
	(uuid(), '635', '635', '76', now(), now()),
	(uuid(), '640', '640', '76', now(), now()),
	(uuid(), '645', '645', '76', now(), now()),
	(uuid(), '760', '760', '76', now(), now()),
	(uuid(), '524', '524', '76', now(), now()),
	(uuid(), '523', '523', '76', now(), now()),
	(uuid(), '518', '518', '76', now(), now()),
	(uuid(), '335', '335', '76', now(), now()),
	(uuid(), '324', '324', '76', now(), now()),
	(uuid(), '323', '323', '76', now(), now()),
	(uuid(), '318', '318', '76', now(), now()),
	(uuid(), '315', '315', '76', now(), now()),
	(uuid(), '123', '123', '76', now(), now()),
	(uuid(), '120', '120', '76', now(), now()),
	(uuid(), '118', '118', '76', now(), now()),
	(uuid(), '116', '116', '76', now(), now()),
	(uuid(), '328 I', '328 I', '76', now(), now()),
	(uuid(), '740 LI', '740 LI', '76', now(), now()),
	(uuid(), 'X5.', 'X5.', '76', now(), now()),
	(uuid(), '528 I', '528 I', '76', now(), now()),
	(uuid(), '750LI', '750LI', '76', now(), now()),
	(uuid(), 'MINI COOPER', 'MINI COOPER', '76', now(), now()),
	(uuid(), '528I', '528I', '76', now(), now()),
	(uuid(), '428 I', '428 I', '76', now(), now()),
	(uuid(), '320 I', '320 I', '76', now(), now()),
	(uuid(), '335 I', '335 I', '76', now(), now()),
	(uuid(), '535 I', '535 I', '76', now(), now()),
	(uuid(), '750.I', '750.I', '76', now(), now()),
	(uuid(), '740 I', '740 I', '76', now(), now()),
	(uuid(), 'M6', 'M6', '76', now(), now()),
	(uuid(), '840 I', '840 I', '76', now(), now()),
	(uuid(), '730', '730', '76', now(), now()),
	(uuid(), '525I', '525I', '76', now(), now()),
	(uuid(), '850.', '850.', '76', now(), now()),
	(uuid(), '430 I', '430 I', '76', now(), now()),
	(uuid(), '330 I', '330 I', '76', now(), now()),
	(uuid(), '540 I', '540 I', '76', now(), now()),
	(uuid(), 'I3', 'I3', '76', now(), now()),
	(uuid(), '520 I', '520 I', '76', now(), now()),
	(uuid(), 'X 1', 'X 1', '76', now(), now()),
	(uuid(), '420 I', '420 I', '76', now(), now()),
	(uuid(), 'M 5', 'M 5', '76', now(), now()),
	(uuid(), 'M850I', 'M850I', '76', now(), now()),
	(uuid(), 'X4 M', 'X4 M', '76', now(), now()),
	(uuid(), '730 LI', '730 LI', '76', now(), now()),
	(uuid(), 'X6  M50I', 'X6  M50I', '76', now(), now()),
	(uuid(), '335XI', '335XI', '76', now(), now()),
	(uuid(), 'X,7', 'X,7', '76', now(), now()),
	(uuid(), 'M 140I', 'M 140I', '76', now(), now()),
	(uuid(), '218 I', '218 I', '76', now(), now()),
	(uuid(), 'M340I', 'M340I', '76', now(), now()),
	(uuid(), '440 I', '440 I', '76', now(), now()),
	(uuid(), '840I', '840I', '76', now(), now()),
	(uuid(), 'X6 M', 'X6 M', '76', now(), now()),
	(uuid(), 'M8', 'M8', '76', now(), now()),
	(uuid(), 'M440I', 'M440I', '76', now(), now()),
	(uuid(), 'AURION', 'AURION', '77', now(), now()),
	(uuid(), 'CAMRY', 'CAMRY', '77', now(), now()),
	(uuid(), 'AVALON', 'AVALON', '77', now(), now()),
	(uuid(), 'CROWN', 'CROWN', '77', now(), now()),
	(uuid(), 'FORTUNER', 'FORTUNER', '77', now(), now()),
	(uuid(), 'HIGHLANDER', 'HIGHLANDER', '77', now(), now()),
	(uuid(), 'LAND CRUISER', 'LAND CRUISER', '77', now(), now()),
	(uuid(), 'PRADO', 'PRADO', '77', now(), now()),
	(uuid(), 'RAV4', 'RAV4', '77', now(), now()),
	(uuid(), 'SEQUOIA', 'SEQUOIA', '77', now(), now()),
	(uuid(), 'VENSA', 'VENSA', '77', now(), now()),
	(uuid(), 'TUNDRA', 'TUNDRA', '77', now(), now()),
	(uuid(), 'AVENSIS', 'AVENSIS', '77', now(), now()),
	(uuid(), 'INNOVA', 'INNOVA', '77', now(), now()),
	(uuid(), 'COASTER', 'COASTER', '77', now(), now()),
	(uuid(), 'HIACE', 'HIACE', '77', now(), now()),
	(uuid(), 'PREVIA', 'PREVIA', '77', now(), now()),
	(uuid(), 'SIENNA', 'SIENNA', '77', now(), now()),
	(uuid(), 'SERA', 'SERA', '77', now(), now()),
	(uuid(), 'TERCEL', 'TERCEL', '77', now(), now()),
	(uuid(), 'STARLET', 'STARLET', '77', now(), now()),
	(uuid(), 'CELICA', 'CELICA', '77', now(), now()),
	(uuid(), 'SUPRA', 'SUPRA', '77', now(), now()),
	(uuid(), 'CARINA', 'CARINA', '77', now(), now()),
	(uuid(), 'MR2', 'MR2', '77', now(), now()),
	(uuid(), 'PICK UP', 'PICK UP', '77', now(), now()),
	(uuid(), 'HICAE', 'HICAE', '77', now(), now()),
	(uuid(), 'HI ACE', 'HI ACE', '77', now(), now()),
	(uuid(), 'COROLLA', 'COROLLA', '77', now(), now()),
	(uuid(), 'VENZA', 'VENZA', '77', now(), now()),
	(uuid(), '4RUNNER', '4RUNNER', '77', now(), now()),
	(uuid(), 'FJ CRUISER', 'FJ CRUISER', '77', now(), now()),
	(uuid(), 'HILUX', 'HILUX', '77', now(), now()),
	(uuid(), 'ORION', 'ORION', '77', now(), now()),
	(uuid(), 'YARIS.', 'YARIS.', '77', now(), now()),
	(uuid(), 'PRIUS', 'PRIUS', '77', now(), now()),
	(uuid(), 'TACOMA', 'TACOMA', '77', now(), now()),
	(uuid(), 'PROACE VERSO', 'PROACE VERSO', '77', now(), now()),
	(uuid(), 'C-HR', 'C-HR', '77', now(), now()),
	(uuid(), 'ALTIMA', 'ALTIMA', '78', now(), now()),
	(uuid(), 'LEAF', 'LEAF', '78', now(), now()),
	(uuid(), 'SKYLINE', 'SKYLINE', '78', now(), now()),
	(uuid(), 'QASHQAI', 'QASHQAI', '78', now(), now()),
	(uuid(), 'LAFESTA', 'LAFESTA', '78', now(), now()),
	(uuid(), 'LIVINA', 'LIVINA', '78', now(), now()),
	(uuid(), 'URVAN', 'URVAN', '78', now(), now()),
	(uuid(), 'ARMADA', 'ARMADA', '78', now(), now()),
	(uuid(), 'ATLAS', 'ATLAS', '78', now(), now()),
	(uuid(), 'FRONTIER', 'FRONTIER', '78', now(), now()),
	(uuid(), 'NAVARA', 'NAVARA', '78', now(), now()),
	(uuid(), 'TITAN', 'TITAN', '78', now(), now()),
	(uuid(), 'CABSTA', 'CABSTA', '78', now(), now()),
	(uuid(), 'ELGRAND', 'ELGRAND', '78', now(), now()),
	(uuid(), 'SUNNY', 'SUNNY', '78', now(), now()),
	(uuid(), 'TEANA', 'TEANA', '78', now(), now()),
	(uuid(), 'TERRANO', 'TERRANO', '78', now(), now()),
	(uuid(), 'PATHFINDER', 'PATHFINDER', '78', now(), now()),
	(uuid(), 'X-TRAIL', 'X-TRAIL', '78', now(), now()),
	(uuid(), 'X-TERRA', 'X-TERRA', '78', now(), now()),
	(uuid(), 'SERENA', 'SERENA', '78', now(), now()),
	(uuid(), 'PRIMASTAR', 'PRIMASTAR', '78', now(), now()),
	(uuid(), 'ALMERA', 'ALMERA', '78', now(), now()),
	(uuid(), 'VERSA HB', 'VERSA HB', '78', now(), now()),
	(uuid(), 'R383', 'R383', '78', now(), now()),
	(uuid(), '370Z', '370Z', '78', now(), now()),
	(uuid(), 'MEDIUM BUS', 'MEDIUM BUS', '78', now(), now()),
	(uuid(), 'PICK UP.', 'PICK UP.', '78', now(), now()),
	(uuid(), 'GTR', 'GTR', '78', now(), now()),
	(uuid(), 'MAXIMA.', 'MAXIMA.', '78', now(), now()),
	(uuid(), 'MURANO.', 'MURANO.', '78', now(), now()),
	(uuid(), 'JUKE', 'JUKE', '78', now(), now()),
	(uuid(), 'COST', 'COST', '78', now(), now()),
	(uuid(), 'PATROL', 'PATROL', '78', now(), now()),
	(uuid(), 'F 15', 'F 15', '78', now(), now()),
	(uuid(), 'DATSUN', 'DATSUN', '78', now(), now()),
	(uuid(), 'NV350', 'NV350', '78', now(), now()),
	(uuid(), 'SENTRA.', 'SENTRA.', '78', now(), now()),
	(uuid(), 'ROGUE', 'ROGUE', '78', now(), now()),
	(uuid(), 'CONVERTIBLE', 'CONVERTIBLE', '80', now(), now()),
	(uuid(), 'BUG RACE', 'BUG RACE', '80', now(), now()),
	(uuid(), 'VANDERBILT CUP', 'VANDERBILT CUP', '80', now(), now()),
	(uuid(), 'ROADMASTER', 'ROADMASTER', '80', now(), now()),
	(uuid(), 'SPECIAL', 'SPECIAL', '80', now(), now()),
	(uuid(), 'ROADMASTER RIVIERA', 'ROADMASTER RIVIERA', '80', now(), now()),
	(uuid(), 'INVICTA', 'INVICTA', '80', now(), now()),
	(uuid(), 'RIVIERA GS', 'RIVIERA GS', '80', now(), now()),
	(uuid(), 'WILDCAT', 'WILDCAT', '80', now(), now()),
	(uuid(), 'SKYLARK', 'SKYLARK', '80', now(), now()),
	(uuid(), 'ELECTRA', 'ELECTRA', '80', now(), now()),
	(uuid(), 'LESABRE', 'LESABRE', '80', now(), now()),
	(uuid(), 'RIVIERA ELECTRA', 'RIVIERA ELECTRA', '80', now(), now()),
	(uuid(), 'SOMERSET', 'SOMERSET', '80', now(), now()),
	(uuid(), 'REGAL', 'REGAL', '80', now(), now()),
	(uuid(), 'CENTURY', 'CENTURY', '80', now(), now()),
	(uuid(), 'PARK AVENUE', 'PARK AVENUE', '80', now(), now()),
	(uuid(), 'LA', 'LA', '80', now(), now()),
	(uuid(), 'LACROSSE', 'LACROSSE', '80', now(), now()),
	(uuid(), 'ENCLAVE', 'ENCLAVE', '80', now(), now()),
	(uuid(), 'REGAL GS', 'REGAL GS', '80', now(), now()),
	(uuid(), 'Y-JOB', 'Y-JOB', '80', now(), now()),
	(uuid(), 'RAINIER', 'RAINIER', '80', now(), now()),
	(uuid(), 'LUCEME', 'LUCEME', '80', now(), now()),
	(uuid(), 'SKYHAWK', 'SKYHAWK', '80', now(), now()),
	(uuid(), 'TERRAZA', 'TERRAZA', '80', now(), now()),
	(uuid(), 'VERANO', 'VERANO', '80', now(), now()),
	(uuid(), 'ESTATE WAGON', 'ESTATE WAGON', '80', now(), now()),
	(uuid(), 'CASCADA', 'CASCADA', '80', now(), now()),
	(uuid(), 'CIMARRON', 'CIMARRON', '80', now(), now()),
	(uuid(), 'ESCALADE', 'ESCALADE', '81', now(), now()),
	(uuid(), 'CTS-V', 'CTS-V', '81', now(), now()),
	(uuid(), 'SRX', 'SRX', '81', now(), now()),
	(uuid(), 'ELDORADO', 'ELDORADO', '81', now(), now()),
	(uuid(), 'SEVILLE', 'SEVILLE', '81', now(), now()),
	(uuid(), 'XTS', 'XTS', '81', now(), now()),
	(uuid(), 'CATERA', 'CATERA', '81', now(), now()),
	(uuid(), 'CT6 SEDAN', 'CT6 SEDAN', '81', now(), now()),
	(uuid(), 'CTS', 'CTS', '81', now(), now()),
	(uuid(), 'DELEGANCE', 'DELEGANCE', '81', now(), now()),
	(uuid(), 'DEVILLE', 'DEVILLE', '81', now(), now()),
	(uuid(), 'DTS', 'DTS', '81', now(), now()),
	(uuid(), 'ELR', 'ELR', '81', now(), now()),
	(uuid(), 'LIMOUSINE', 'LIMOUSINE', '81', now(), now()),
	(uuid(), 'STS', 'STS', '81', now(), now()),
	(uuid(), 'XLR', 'XLR', '81', now(), now()),
	(uuid(), 'XT5', 'XT5', '81', now(), now()),
	(uuid(), 'ALLANTE', 'ALLANTE', '81', now(), now()),
	(uuid(), 'ATS', 'ATS', '81', now(), now()),
	(uuid(), 'ATS COUPE', 'ATS COUPE', '81', now(), now()),
	(uuid(), 'CONCOURS', 'CONCOURS', '81', now(), now()),
	(uuid(), 'ATS-V COUPE', 'ATS-V COUPE', '81', now(), now()),
	(uuid(), 'ATS-V SEDAN', 'ATS-V SEDAN', '81', now(), now()),
	(uuid(), 'BROUGHAM', 'BROUGHAM', '81', now(), now()),
	(uuid(), 'CT6', 'CT6', '81', now(), now()),
	(uuid(), 'CT4', 'CT4', '81', now(), now()),
	(uuid(), '150', '150', '82', now(), now()),
	(uuid(), '160', '160', '82', now(), now()),
	(uuid(), '300M', '300M', '82', now(), now()),
	(uuid(), '300C', '300C', '82', now(), now()),
	(uuid(), 'AIRSTREAM', 'AIRSTREAM', '82', now(), now()),
	(uuid(), 'ALPINE', 'ALPINE', '82', now(), now()),
	(uuid(), 'ASPEN', 'ASPEN', '82', now(), now()),
	(uuid(), 'AVENGER', 'AVENGER', '82', now(), now()),
	(uuid(), 'CENTURA', 'CENTURA', '82', now(), now()),
	(uuid(), 'CIRRUS', 'CIRRUS', '82', now(), now()),
	(uuid(), 'CONCORDE', 'CONCORDE', '82', now(), now()),
	(uuid(), 'CROSSFIRE', 'CROSSFIRE', '82', now(), now()),
	(uuid(), 'DAYTONA', 'DAYTONA', '82', now(), now()),
	(uuid(), 'D-50', 'D-50', '82', now(), now()),
	(uuid(), 'DRIFTER', 'DRIFTER', '82', now(), now()),
	(uuid(), 'FIFTH AVENUE', 'FIFTH AVENUE', '82', now(), now()),
	(uuid(), 'INTREPID', 'INTREPID', '82', now(), now()),
	(uuid(), 'L300 EXPRESS', 'L300 EXPRESS', '82', now(), now()),
	(uuid(), 'CHRYSLER LASER', 'CHRYSLER LASER', '82', now(), now()),
	(uuid(), 'GRAND VOYAGER', 'GRAND VOYAGER', '82', now(), now()),
	(uuid(), 'VIPER', 'VIPER', '82', now(), now()),
	(uuid(), 'VIP', 'VIP', '82', now(), now()),
	(uuid(), 'VOGUE', 'VOGUE', '82', now(), now()),
	(uuid(), 'VALIANT', 'VALIANT', '82', now(), now()),
	(uuid(), 'TOWN AND COUNTRY', 'TOWN AND COUNTRY', '82', now(), now()),
	(uuid(), 'CHRYSLER TOURING', 'CHRYSLER TOURING', '82', now(), now()),
	(uuid(), 'TURBINE', 'TURBINE', '82', now(), now()),
	(uuid(), 'CHRYSLER WINDSOR', 'CHRYSLER WINDSOR', '82', now(), now()),
	(uuid(), 'NEW YORKER FIFTH', 'NEW YORKER FIFTH', '82', now(), now()),
	(uuid(), 'FIFTH', 'FIFTH', '82', now(), now()),
	(uuid(), 'PACIFIC', 'PACIFIC', '82', now(), now()),
	(uuid(), 'PACIFICA', 'PACIFICA', '82', now(), now()),
	(uuid(), 'SUNBEAM CAR', 'SUNBEAM CAR', '82', now(), now()),
	(uuid(), 'SEBRING', 'SEBRING', '82', now(), now()),
	(uuid(), 'PLAINSMAN', 'PLAINSMAN', '82', now(), now()),
	(uuid(), '300 S', '300 S', '82', now(), now()),
	(uuid(), '200 C', '200 C', '82', now(), now()),
	(uuid(), '300', '300', '82', now(), now()),
	(uuid(), '300 LIMITED', '300 LIMITED', '82', now(), now()),
	(uuid(), '200 TOURING', '200 TOURING', '82', now(), now()),
	(uuid(), '300 G', '300 G', '82', now(), now()),
	(uuid(), '200,', '200,', '82', now(), now()),
	(uuid(), '500,', '500,', '82', now(), now()),
	(uuid(), 'GRAND CARAVAN', 'GRAND CARAVAN', '83', now(), now()),
	(uuid(), 'DODGE DART', 'DODGE DART', '83', now(), now()),
	(uuid(), 'JOURNEY BACKTOP', 'JOURNEY BACKTOP', '83', now(), now()),
	(uuid(), 'ARCHIVES', 'ARCHIVES', '83', now(), now()),
	(uuid(), 'DURANGO', 'DURANGO', '83', now(), now()),
	(uuid(), 'CARAVAN', 'CARAVAN', '83', now(), now()),
	(uuid(), 'CHARGER REDLINE', 'CHARGER REDLINE', '83', now(), now()),
	(uuid(), 'JOURNEY CROSSROAD', 'JOURNEY CROSSROAD', '83', now(), now()),
	(uuid(), 'CORONET', 'CORONET', '83', now(), now()),
	(uuid(), 'VIPER SRT', 'VIPER SRT', '83', now(), now()),
	(uuid(), 'RAM PICK UP', 'RAM PICK UP', '83', now(), now()),
	(uuid(), 'CHALLENGER SHAKER', 'CHALLENGER SHAKER', '83', now(), now()),
	(uuid(), 'NITRO', 'NITRO', '83', now(), now()),
	(uuid(), 'MAGNUM', 'MAGNUM', '83', now(), now()),
	(uuid(), 'CALIBER', 'CALIBER', '83', now(), now()),
	(uuid(), 'DART', 'DART', '83', now(), now()),
	(uuid(), 'CHALLENGER.', 'CHALLENGER.', '83', now(), now()),
	(uuid(), 'CHARGER', 'CHARGER', '83', now(), now()),
	(uuid(), 'DART RALLYE / SXT', 'DART RALLYE / SXT', '83', now(), now()),
	(uuid(), 'JOURNEY', 'JOURNEY', '83', now(), now()),
	(uuid(), 'RAM 1500', 'RAM 1500', '83', now(), now()),
	(uuid(), '40 I T I', '40 I T I', '84', now(), now()),
	(uuid(), 'XF', 'XF', '84', now(), now()),
	(uuid(), 'SAVANA 2500', 'SAVANA 2500', '85', now(), now()),
	(uuid(), 'SIERRA 1500', 'SIERRA 1500', '85', now(), now()),
	(uuid(), 'ACADIA', 'ACADIA', '85', now(), now()),
	(uuid(), 'YUKON', 'YUKON', '85', now(), now()),
	(uuid(), 'YUKON XL', 'YUKON XL', '85', now(), now()),
	(uuid(), 'TERRAIN', 'TERRAIN', '85', now(), now()),
	(uuid(), 'ASTRO', 'ASTRO', '85', now(), now()),
	(uuid(), 'JIMMY', 'JIMMY', '85', now(), now()),
	(uuid(), 'ENVOY', 'ENVOY', '85', now(), now()),
	(uuid(), 'SAFARY', 'SAFARY', '85', now(), now()),
	(uuid(), 'SUBURBAN', 'SUBURBAN', '85', now(), now()),
	(uuid(), 'K5', 'K5', '85', now(), now()),
	(uuid(), 'Z7', 'Z7', '85', now(), now()),
	(uuid(), 'DENALI', 'DENALI', '85', now(), now()),
	(uuid(), 'SAVANA', 'SAVANA', '85', now(), now()),
	(uuid(), 'SIERRA', 'SIERRA', '85', now(), now()),
	(uuid(), 'YUKON DENALI', 'YUKON DENALI', '85', now(), now()),
	(uuid(), 'SIERRA 3500HD', 'SIERRA 3500HD', '85', now(), now()),
	(uuid(), 'YUKON XL DENALI', 'YUKON XL DENALI', '85', now(), now()),
	(uuid(), 'FALCON', 'FALCON', '86', now(), now()),
	(uuid(), 'FIESTA', 'FIESTA', '86', now(), now()),
	(uuid(), 'FIGO', 'FIGO', '86', now(), now()),
	(uuid(), 'FOCUS', 'FOCUS', '86', now(), now()),
	(uuid(), 'FUSION', 'FUSION', '86', now(), now()),
	(uuid(), 'MONDEO', 'MONDEO', '86', now(), now()),
	(uuid(), 'MUSTANG', 'MUSTANG', '86', now(), now()),
	(uuid(), 'TAURUS', 'TAURUS', '86', now(), now()),
	(uuid(), 'C-MAX', 'C-MAX', '86', now(), now()),
	(uuid(), 'S-MAX', 'S-MAX', '86', now(), now()),
	(uuid(), 'GALAXY', 'GALAXY', '86', now(), now()),
	(uuid(), 'ESCAPE', 'ESCAPE', '86', now(), now()),
	(uuid(), 'ECO SPORT', 'ECO SPORT', '86', now(), now()),
	(uuid(), 'EDGE', 'EDGE', '86', now(), now()),
	(uuid(), 'FLEX', 'FLEX', '86', now(), now()),
	(uuid(), 'EVEREST', 'EVEREST', '86', now(), now()),
	(uuid(), 'EXPLORER', 'EXPLORER', '86', now(), now()),
	(uuid(), 'EXPEDITION', 'EXPEDITION', '86', now(), now()),
	(uuid(), 'KUGA', 'KUGA', '86', now(), now()),
	(uuid(), 'TERRITORY', 'TERRITORY', '86', now(), now()),
	(uuid(), 'CROWN VICTORIA', 'CROWN VICTORIA', '86', now(), now()),
	(uuid(), 'AEROSTAR', 'AEROSTAR', '86', now(), now()),
	(uuid(), 'RANGER', 'RANGER', '86', now(), now()),
	(uuid(), 'PROBE', 'PROBE', '86', now(), now()),
	(uuid(), 'TEMPO', 'TEMPO', '86', now(), now()),
	(uuid(), 'VAN', 'VAN', '86', now(), now()),
	(uuid(), 'WINDSTAR', 'WINDSTAR', '86', now(), now()),
	(uuid(), 'ZX2', 'ZX2', '86', now(), now()),
	(uuid(), 'BRONCO', 'BRONCO', '86', now(), now()),
	(uuid(), 'FREESTAR', 'FREESTAR', '86', now(), now()),
	(uuid(), 'ESCORT', 'ESCORT', '86', now(), now()),
	(uuid(), 'EXCURSION', 'EXCURSION', '86', now(), now()),
	(uuid(), 'FESTIVA', 'FESTIVA', '86', now(), now()),
	(uuid(), 'ECONOLINE', 'ECONOLINE', '86', now(), now()),
	(uuid(), 'ECONOLINE E350', 'ECONOLINE E350', '86', now(), now()),
	(uuid(), 'F150', 'F150', '86', now(), now()),
	(uuid(), 'F 250', 'F 250', '86', now(), now()),
	(uuid(), 'MOTORHOME', 'MOTORHOME', '86', now(), now()),
	(uuid(), 'TRANSIT', 'TRANSIT', '86', now(), now()),
	(uuid(), 'F-350', 'F-350', '86', now(), now()),
	(uuid(), 'ROUSH', 'ROUSH', '86', now(), now()),
	(uuid(), 'MOTOR HOME', 'MOTOR HOME', '86', now(), now()),
	(uuid(), 'E-350', 'E-350', '86', now(), now()),
	(uuid(), 'F-550', 'F-550', '86', now(), now()),
	(uuid(), 'TAURUS S E', 'TAURUS S E', '86', now(), now()),
	(uuid(), 'MUSTANG GT', 'MUSTANG GT', '86', now(), now()),
	(uuid(), '1833.', '1833.', '86', now(), now()),
	(uuid(), '750 MONZA', '750 MONZA', '87', now(), now()),
	(uuid(), 'BARCHETTA', 'BARCHETTA', '87', now(), now()),
	(uuid(), '312PB', '312PB', '87', now(), now()),
	(uuid(), 'TESTA ROSSA', 'TESTA ROSSA', '87', now(), now()),
	(uuid(), '330 LMB', '330 LMB', '87', now(), now()),
	(uuid(), '458 ITALIA', '458 ITALIA', '87', now(), now()),
	(uuid(), '360', '360', '87', now(), now()),
	(uuid(), '430', '430', '87', now(), now()),
	(uuid(), '575 MARANELLO', '575 MARANELLO', '87', now(), now()),
	(uuid(), '599', '599', '87', now(), now()),
	(uuid(), '599 GTB FIORANO', '599 GTB FIORANO', '87', now(), now()),
	(uuid(), '612 SCAGLIETTI', '612 SCAGLIETTI', '87', now(), now()),
	(uuid(), 'CALIFORNIA', 'CALIFORNIA', '87', now(), now()),
	(uuid(), 'ENZO', 'ENZO', '87', now(), now()),
	(uuid(), 'F12 BERLINETTA', 'F12 BERLINETTA', '87', now(), now()),
	(uuid(), 'FF', 'FF', '87', now(), now()),
	(uuid(), 'LAFERRARI', 'LAFERRARI', '87', now(), now()),
	(uuid(), 'ROMA', 'ROMA', '87', now(), now()),
	(uuid(), 'CHEROKEE', 'CHEROKEE', '88', now(), now()),
	(uuid(), 'GRAND CHEROKEE', 'GRAND CHEROKEE', '88', now(), now()),
	(uuid(), 'COMPASS', 'COMPASS', '88', now(), now()),
	(uuid(), 'CHEROKEE SRT', 'CHEROKEE SRT', '88', now(), now()),
	(uuid(), 'PATRIOT', 'PATRIOT', '88', now(), now()),
	(uuid(), 'RENEGADE', 'RENEGADE', '88', now(), now()),
	(uuid(), 'WRANGLER', 'WRANGLER', '88', now(), now()),
	(uuid(), 'LIBERTY', 'LIBERTY', '88', now(), now()),
	(uuid(), 'COMANDO', 'COMANDO', '88', now(), now()),
	(uuid(), 'WAGONEER', 'WAGONEER', '88', now(), now()),
	(uuid(), 'ACCORD', 'ACCORD', '89', now(), now()),
	(uuid(), 'CIVIC', 'CIVIC', '89', now(), now()),
	(uuid(), 'CITY', 'CITY', '89', now(), now()),
	(uuid(), 'JAZZ', 'JAZZ', '89', now(), now()),
	(uuid(), 'STREAM', 'STREAM', '89', now(), now()),
	(uuid(), 'PILOT', 'PILOT', '89', now(), now()),
	(uuid(), 'ODYSSEY', 'ODYSSEY', '89', now(), now()),
	(uuid(), 'INSPIRE', 'INSPIRE', '89', now(), now()),
	(uuid(), 'CR-V', 'CR-V', '89', now(), now()),
	(uuid(), 'CR-Z', 'CR-Z', '89', now(), now()),
	(uuid(), 'CAREN', 'CAREN', '89', now(), now()),
	(uuid(), 'BRIO', 'BRIO', '89', now(), now()),
	(uuid(), 'BALLADE', 'BALLADE', '89', now(), now()),
	(uuid(), 'AIRWAVE', 'AIRWAVE', '89', now(), now()),
	(uuid(), 'MV-99', 'MV-99', '89', now(), now()),
	(uuid(), 'CONTOUR', 'CONTOUR', '89', now(), now()),
	(uuid(), 'MRV', 'MRV', '89', now(), now()),
	(uuid(), 'HRV', 'HRV', '89', now(), now()),
	(uuid(), 'PRELUDE', 'PRELUDE', '89', now(), now()),
	(uuid(), 'QUINTET', 'QUINTET', '89', now(), now()),
	(uuid(), 'CRX', 'CRX', '89', now(), now()),
	(uuid(), 'CROSSTOUR', 'CROSSTOUR', '89', now(), now()),
	(uuid(), 'ELEMENT', 'ELEMENT', '89', now(), now()),
	(uuid(), 'CONCERTO', 'CONCERTO', '89', now(), now()),
	(uuid(), 'ACCENT', 'ACCENT', '90', now(), now()),
	(uuid(), 'ATOS', 'ATOS', '90', now(), now()),
	(uuid(), 'ELANTRA', 'ELANTRA', '90', now(), now()),
	(uuid(), 'EXCEL', 'EXCEL', '90', now(), now()),
	(uuid(), 'LAVITA', 'LAVITA', '90', now(), now()),
	(uuid(), 'GENESIS', 'GENESIS', '90', now(), now()),
	(uuid(), 'GENESIS COUPE', 'GENESIS COUPE', '90', now(), now()),
	(uuid(), 'GETZ', 'GETZ', '90', now(), now()),
	(uuid(), 'GRANDEUR', 'GRANDEUR', '90', now(), now()),
	(uuid(), 'HB20', 'HB20', '90', now(), now()),
	(uuid(), 'I10', 'I10', '90', now(), now()),
	(uuid(), 'I20', 'I20', '90', now(), now()),
	(uuid(), 'I30', 'I30', '90', now(), now()),
	(uuid(), 'I40', 'I40', '90', now(), now()),
	(uuid(), 'IX20', 'IX20', '90', now(), now()),
	(uuid(), 'MISTRA', 'MISTRA', '90', now(), now()),
	(uuid(), 'NUVIS', 'NUVIS', '90', now(), now()),
	(uuid(), 'SCOUPE', 'SCOUPE', '90', now(), now()),
	(uuid(), 'SONATA', 'SONATA', '90', now(), now()),
	(uuid(), 'STELLAR', 'STELLAR', '90', now(), now()),
	(uuid(), 'VELOSTER', 'VELOSTER', '90', now(), now()),
	(uuid(), 'VERACRUZ', 'VERACRUZ', '90', now(), now()),
	(uuid(), 'TIBURON', 'TIBURON', '90', now(), now()),
	(uuid(), 'DYNASTY', 'DYNASTY', '90', now(), now()),
	(uuid(), 'BLUE-WILL', 'BLUE-WILL', '90', now(), now()),
	(uuid(), 'CENTENNIAL', 'CENTENNIAL', '90', now(), now()),
	(uuid(), 'GALLOPER', 'GALLOPER', '90', now(), now()),
	(uuid(), 'AZERA', 'AZERA', '90', now(), now()),
	(uuid(), 'SANTA FE', 'SANTA FE', '90', now(), now()),
	(uuid(), 'GRAND SANTA FE', 'GRAND SANTA FE', '90', now(), now()),
	(uuid(), 'GLORIA', 'GLORIA', '90', now(), now()),
	(uuid(), 'H350', 'H350', '90', now(), now()),
	(uuid(), 'H-1', 'H-1', '90', now(), now()),
	(uuid(), 'FX', 'FX', '90', now(), now()),
	(uuid(), 'STAREX', 'STAREX', '90', now(), now()),
	(uuid(), 'CRETA', 'CRETA', '90', now(), now()),
	(uuid(), 'AVANTE', 'AVANTE', '90', now(), now()),
	(uuid(), 'HD65', 'HD65', '90', now(), now()),
	(uuid(), 'TUCSON', 'TUCSON', '90', now(), now()),
	(uuid(), 'GRAND STAREX', 'GRAND STAREX', '90', now(), now()),
	(uuid(), 'PORTER II', 'PORTER II', '90', now(), now()),
	(uuid(), 'KONA', 'KONA', '90', now(), now()),
	(uuid(), 'PALISADE', 'PALISADE', '90', now(), now()),
	(uuid(), 'STARIA', 'STARIA', '90', now(), now()),
	(uuid(), 'KM420', 'KM420', '91', now(), now()),
	(uuid(), 'CADENZA', 'CADENZA', '91', now(), now()),
	(uuid(), 'RIO', 'RIO', '91', now(), now()),
	(uuid(), 'PICANTO', 'PICANTO', '91', now(), now()),
	(uuid(), 'RONDO', 'RONDO', '91', now(), now()),
	(uuid(), 'BORREGO', 'BORREGO', '91', now(), now()),
	(uuid(), 'FORTE', 'FORTE', '91', now(), now()),
	(uuid(), 'VENGA', 'VENGA', '91', now(), now()),
	(uuid(), 'SOUL', 'SOUL', '91', now(), now()),
	(uuid(), 'PRIDE', 'PRIDE', '91', now(), now()),
	(uuid(), 'OPTIMA', 'OPTIMA', '91', now(), now()),
	(uuid(), 'CERATO', 'CERATO', '91', now(), now()),
	(uuid(), 'FORTE KOUP', 'FORTE KOUP', '91', now(), now()),
	(uuid(), 'SPORTAGE', 'SPORTAGE', '91', now(), now()),
	(uuid(), 'SPECTRA', 'SPECTRA', '91', now(), now()),
	(uuid(), 'RAY', 'RAY', '91', now(), now()),
	(uuid(), 'OPIRUS', 'OPIRUS', '91', now(), now()),
	(uuid(), 'MOHAVE', 'MOHAVE', '91', now(), now()),
	(uuid(), 'SEPHIA', 'SEPHIA', '91', now(), now()),
	(uuid(), 'CONCORD', 'CONCORD', '91', now(), now()),
	(uuid(), 'BRISA', 'BRISA', '91', now(), now()),
	(uuid(), 'SAIPA', 'SAIPA', '91', now(), now()),
	(uuid(), 'QOURIS', 'QOURIS', '91', now(), now()),
	(uuid(), 'CLARUS', 'CLARUS', '91', now(), now()),
	(uuid(), 'CEED', 'CEED', '91', now(), now()),
	(uuid(), 'BINGO', 'BINGO', '91', now(), now()),
	(uuid(), 'AVILA', 'AVILA', '91', now(), now()),
	(uuid(), 'RINO', 'RINO', '91', now(), now()),
	(uuid(), 'SEDONA', 'SEDONA', '91', now(), now()),
	(uuid(), 'CARNIVAL', 'CARNIVAL', '91', now(), now()),
	(uuid(), 'CARENS', 'CARENS', '91', now(), now()),
	(uuid(), 'SORENTO', 'SORENTO', '91', now(), now()),
	(uuid(), 'K-5', 'K-5', '91', now(), now()),
	(uuid(), 'K-7', 'K-7', '91', now(), now()),
	(uuid(), 'QUORIS', 'QUORIS', '91', now(), now()),
	(uuid(), 'K-3', 'K-3', '91', now(), now()),
	(uuid(), 'BONGO', 'BONGO', '91', now(), now()),
	(uuid(), 'STINGER', 'STINGER', '91', now(), now()),
	(uuid(), 'STONIC', 'STONIC', '91', now(), now()),
	(uuid(), 'ADVENTURE', 'ADVENTURE', '92', now(), now()),
	(uuid(), 'ASPIRE', 'ASPIRE', '92', now(), now()),
	(uuid(), 'GALANT', 'GALANT', '92', now(), now()),
	(uuid(), 'LANCER', 'LANCER', '92', now(), now()),
	(uuid(), 'SIGMA', 'SIGMA', '92', now(), now()),
	(uuid(), 'TREDIA', 'TREDIA', '92', now(), now()),
	(uuid(), 'OUTLANDER', 'OUTLANDER', '92', now(), now()),
	(uuid(), 'PAJERO', 'PAJERO', '92', now(), now()),
	(uuid(), 'STRADA', 'STRADA', '92', now(), now()),
	(uuid(), 'LIBERO', 'LIBERO', '92', now(), now()),
	(uuid(), 'DELICA', 'DELICA', '92', now(), now()),
	(uuid(), 'CORDIA', 'CORDIA', '92', now(), now()),
	(uuid(), 'CHARIOT', 'CHARIOT', '92', now(), now()),
	(uuid(), 'CHALLENGER', 'CHALLENGER', '92', now(), now()),
	(uuid(), 'ECLIPSE', 'ECLIPSE', '92', now(), now()),
	(uuid(), 'LEGNUM', 'LEGNUM', '92', now(), now()),
	(uuid(), 'CARISMA', 'CARISMA', '92', now(), now()),
	(uuid(), 'DEBONAIR', 'DEBONAIR', '92', now(), now()),
	(uuid(), 'DIAMANTE', 'DIAMANTE', '92', now(), now()),
	(uuid(), 'NATIVA', 'NATIVA', '92', now(), now()),
	(uuid(), 'MONTERO', 'MONTERO', '92', now(), now()),
	(uuid(), 'SPACE WAGON', 'SPACE WAGON', '92', now(), now()),
	(uuid(), 'MAGNA', 'MAGNA', '92', now(), now()),
	(uuid(), 'GRANDIS', 'GRANDIS', '92', now(), now()),
	(uuid(), 'L200', 'L200', '92', now(), now()),
	(uuid(), 'EVOLUTION', 'EVOLUTION', '92', now(), now()),
	(uuid(), '304', '304', '92', now(), now()),
	(uuid(), 'L 300', 'L 300', '92', now(), now()),
	(uuid(), 'L 200', 'L 200', '92', now(), now()),
	(uuid(), 'FUSO', 'FUSO', '92', now(), now()),
	(uuid(), 'CANTER', 'CANTER', '92', now(), now()),
	(uuid(), 'MONTERO SPORT', 'MONTERO SPORT', '92', now(), now()),
	(uuid(), 'ATTRAGE', 'ATTRAGE', '92', now(), now()),
	(uuid(), 'ECLIPSE CROSS', 'ECLIPSE CROSS', '92', now(), now()),
	(uuid(), 'COOPER', 'COOPER', '93', now(), now()),
	(uuid(), 'MK 1 COOPER', 'MK 1 COOPER', '93', now(), now()),
	(uuid(), 'MK 2 COOPER', 'MK 2 COOPER', '93', now(), now()),
	(uuid(), 'MINI HATCH', 'MINI HATCH', '93', now(), now()),
	(uuid(), 'COUNTRYMAN', 'COUNTRYMAN', '93', now(), now()),
	(uuid(), 'MOKE', 'MOKE', '93', now(), now()),
	(uuid(), 'COOPER S', 'COOPER S', '93', now(), now()),
	(uuid(), 'CLUBMAN', 'CLUBMAN', '93', now(), now()),
	(uuid(), 'AVENTOR', 'AVENTOR', '94', now(), now()),
	(uuid(), 'BICOLORE GALLARDO', 'BICOLORE GALLARDO', '94', now(), now()),
	(uuid(), 'COUNTACH LP400', 'COUNTACH LP400', '94', now(), now()),
	(uuid(), 'ESPADA', 'ESPADA', '94', now(), now()),
	(uuid(), 'DIABLO', 'DIABLO', '94', now(), now()),
	(uuid(), 'GALLARDO', 'GALLARDO', '94', now(), now()),
	(uuid(), 'MURCIELAGO', 'MURCIELAGO', '94', now(), now()),
	(uuid(), 'HURACAN', 'HURACAN', '94', now(), now()),
	(uuid(), 'SESTO ELEMENTO', 'SESTO ELEMENTO', '94', now(), now()),
	(uuid(), 'VENENO', 'VENENO', '94', now(), now()),
	(uuid(), 'YETI', 'YETI', '95', now(), now()),
	(uuid(), 'ROOMSTER', 'ROOMSTER', '95', now(), now()),
	(uuid(), 'SUPERB', 'SUPERB', '95', now(), now()),
	(uuid(), 'RAPID', 'RAPID', '95', now(), now()),
	(uuid(), 'FABIA', 'FABIA', '95', now(), now()),
	(uuid(), 'MISSION', 'MISSION', '95', now(), now()),
	(uuid(), 'JOYSTER', 'JOYSTER', '95', now(), now()),
	(uuid(), 'FELICIA', 'FELICIA', '95', now(), now()),
	(uuid(), 'OCTAVIA', 'OCTAVIA', '95', now(), now()),
	(uuid(), '130', '130', '95', now(), now()),
	(uuid(), '135', '135', '95', now(), now()),
	(uuid(), '136', '136', '95', now(), now()),
	(uuid(), 'GARDE', 'GARDE', '95', now(), now()),
	(uuid(), '110 R', '110 R', '95', now(), now()),
	(uuid(), 'FAVORIT', 'FAVORIT', '95', now(), now()),
	(uuid(), '10HP', '10HP', '97', now(), now()),
	(uuid(), '15HP', '15HP', '97', now(), now()),
	(uuid(), '25/30 PHANTOM 1', '25/30 PHANTOM 1', '97', now(), now()),
	(uuid(), 'PARK AWARD', 'PARK AWARD', '97', now(), now()),
	(uuid(), 'GHOST.', 'GHOST.', '97', now(), now()),
	(uuid(), 'CULLINAN', 'CULLINAN', '97', now(), now()),
	(uuid(), 'XJ', 'XJ', '98', now(), now()),
	(uuid(), 'F-TYPE', 'F-TYPE', '98', now(), now()),
	(uuid(), 'XF,', 'XF,', '98', now(), now()),
	(uuid(), 'XJL', 'XJL', '98', now(), now()),
	(uuid(), '480-26', '480-26', '99', now(), now()),
	(uuid(), 'MIXER.', 'MIXER.', '99', now(), now()),
	(uuid(), '33-400', '33-400', '99', now(), now()),
	(uuid(), 'TGA 26.440', 'TGA 26.440', '99', now(), now()),
	(uuid(), '41440', '41440', '99', now(), now()),
	(uuid(), 'TGM 18.330', 'TGM 18.330', '99', now(), now()),
	(uuid(), 'TGX26.440', 'TGX26.440', '99', now(), now()),
	(uuid(), 'TGA.35.400', 'TGA.35.400', '99', now(), now()),
	(uuid(), 'TGS.18.440', 'TGS.18.440', '99', now(), now()),
	(uuid(), 'TXG18.440', 'TXG18.440', '99', now(), now()),
	(uuid(), 'TGX-18.440', 'TGX-18.440', '99', now(), now()),
	(uuid(), 'TGX.18.440', 'TGX.18.440', '99', now(), now()),
	(uuid(), 'TGX 26.400', 'TGX 26.400', '99', now(), now()),
	(uuid(), 'TGX 18.400', 'TGX 18.400', '99', now(), now()),
	(uuid(), 'TGX 18.360', 'TGX 18.360', '99', now(), now()),
	(uuid(), 'TGL 12.180', 'TGL 12.180', '99', now(), now()),
	(uuid(), 'TGS.18.400', 'TGS.18.400', '99', now(), now()),
	(uuid(), 'TGS 26.400', 'TGS 26.400', '99', now(), now()),
	(uuid(), 'TGX 10.480', 'TGX 10.480', '99', now(), now()),
	(uuid(), 'TGS 26.440', 'TGS 26.440', '99', now(), now()),
	(uuid(), 'TGX 18.480', 'TGX 18.480', '99', now(), now()),
	(uuid(), 'TGA 26.430', 'TGA 26.430', '99', now(), now()),
	(uuid(), 'TGS 35.400', 'TGS 35.400', '99', now(), now()),
	(uuid(), 'TGS 18.480', 'TGS 18.480', '99', now(), now()),
	(uuid(), 'TGS 33.400', 'TGS 33.400', '99', now(), now()),
	(uuid(), 'TGS.18.420', 'TGS.18.420', '99', now(), now()),
	(uuid(), 'TGM 18.340', 'TGM 18.340', '99', now(), now()),
	(uuid(), 'TGS 18.460', 'TGS 18.460', '99', now(), now()),
	(uuid(), 'TGS 18.320', 'TGS 18.320', '99', now(), now()),
	(uuid(), 'TGX 18.460', 'TGX 18.460', '99', now(), now()),
	(uuid(), 'TGX 18.500', 'TGX 18.500', '99', now(), now()),
	(uuid(), 'TGX26.500', 'TGX26.500', '99', now(), now()),
	(uuid(), 'TGX 18.430', 'TGX 18.430', '99', now(), now()),
	(uuid(), 'TGS 26.420', 'TGS 26.420', '99', now(), now()),
	(uuid(), 'TGX 26.460', 'TGX 26.460', '99', now(), now()),
	(uuid(), 'TGX 18.420', 'TGX 18.420', '99', now(), now()),
	(uuid(), '4300', '4300', '100', now(), now()),
	(uuid(), '7300', '7300', '100', now(), now()),
	(uuid(), 'LARGE TRUCK', 'LARGE TRUCK', '103', now(), now()),
	(uuid(), 'MEDIUM TRUCK', 'MEDIUM TRUCK', '103', now(), now()),
	(uuid(), 'TAHOE', 'TAHOE', '104', now(), now()),
	(uuid(), 'TRAVERSE', 'TRAVERSE', '104', now(), now()),
	(uuid(), 'AVEO', 'AVEO', '104', now(), now()),
	(uuid(), 'CRUZE', 'CRUZE', '104', now(), now()),
	(uuid(), 'CAMARO', 'CAMARO', '104', now(), now()),
	(uuid(), 'CORVETTE', 'CORVETTE', '104', now(), now()),
	(uuid(), 'MALIBU', 'MALIBU', '104', now(), now()),
	(uuid(), 'IMPALA', 'IMPALA', '104', now(), now()),
	(uuid(), 'SPARK', 'SPARK', '104', now(), now()),
	(uuid(), 'CAPTIVA', 'CAPTIVA', '104', now(), now()),
	(uuid(), 'AVALANCHE', 'AVALANCHE', '104', now(), now()),
	(uuid(), 'CHEVELLE', 'CHEVELLE', '104', now(), now()),
	(uuid(), 'CAPRICE', 'CAPRICE', '104', now(), now()),
	(uuid(), 'CAVALIER', 'CAVALIER', '104', now(), now()),
	(uuid(), 'CELEBRITY', 'CELEBRITY', '104', now(), now()),
	(uuid(), 'CITATION', 'CITATION', '104', now(), now()),
	(uuid(), 'COLORADO', 'COLORADO', '104', now(), now()),
	(uuid(), 'CORSICA', 'CORSICA', '104', now(), now()),
	(uuid(), 'EPICA', 'EPICA', '104', now(), now()),
	(uuid(), 'EQUINOX', 'EQUINOX', '104', now(), now()),
	(uuid(), 'FONTERA', 'FONTERA', '104', now(), now()),
	(uuid(), 'LUMINA', 'LUMINA', '104', now(), now()),
	(uuid(), 'OPTRA', 'OPTRA', '104', now(), now()),
	(uuid(), 'SILVERADO', 'SILVERADO', '104', now(), now()),
	(uuid(), 'TRAIL BLAZER', 'TRAIL BLAZER', '104', now(), now()),
	(uuid(), 'UPLANDER', 'UPLANDER', '104', now(), now()),
	(uuid(), 'SONIC', 'SONIC', '104', now(), now()),
	(uuid(), 'SPRINT', 'SPRINT', '104', now(), now()),
	(uuid(), 'SUBURBAN.', 'SUBURBAN.', '104', now(), now()),
	(uuid(), 'EXPRESS', 'EXPRESS', '104', now(), now()),
	(uuid(), '2500.', '2500.', '104', now(), now()),
	(uuid(), 'MOTOR - HOME', 'MOTOR - HOME', '104', now(), now()),
	(uuid(), 'COBALT LTZ', 'COBALT LTZ', '104', now(), now()),
	(uuid(), 'RANGE ROVER', 'RANGE ROVER', '105', now(), now()),
	(uuid(), 'DEPENDER', 'DEPENDER', '105', now(), now()),
	(uuid(), 'DEFENDER', 'DEFENDER', '105', now(), now()),
	(uuid(), 'RANGE ROVER SPORT', 'RANGE ROVER SPORT', '105', now(), now()),
	(uuid(), 'RANGE ROVER EVOQUE', 'RANGE ROVER EVOQUE', '105', now(), now()),
	(uuid(), 'RANGE ROVER VELAR', 'RANGE ROVER VELAR', '105', now(), now()),
	(uuid(), 'ES 350', 'ES 350', '106', now(), now()),
	(uuid(), 'CT 200H', 'CT 200H', '106', now(), now()),
	(uuid(), 'IS 200', 'IS 200', '106', now(), now()),
	(uuid(), 'IS 300', 'IS 300', '106', now(), now()),
	(uuid(), 'IS 250', 'IS 250', '106', now(), now()),
	(uuid(), 'IS 220D', 'IS 220D', '106', now(), now()),
	(uuid(), 'IS 350', 'IS 350', '106', now(), now()),
	(uuid(), 'IS 300H', 'IS 300H', '106', now(), now()),
	(uuid(), 'IS 200T', 'IS 200T', '106', now(), now()),
	(uuid(), 'HS 250H', 'HS 250H', '106', now(), now()),
	(uuid(), 'ES 250', 'ES 250', '106', now(), now()),
	(uuid(), 'ES 300', 'ES 300', '106', now(), now()),
	(uuid(), 'ES 240', 'ES 240', '106', now(), now()),
	(uuid(), 'ES 200', 'ES 200', '106', now(), now()),
	(uuid(), 'GS 300', 'GS 300', '106', now(), now()),
	(uuid(), 'GS 400', 'GS 400', '106', now(), now()),
	(uuid(), 'GS 430', 'GS 430', '106', now(), now()),
	(uuid(), 'GS 350', 'GS 350', '106', now(), now()),
	(uuid(), 'LS 460', 'LS 460', '106', now(), now()),
	(uuid(), 'RX 350', 'RX 350', '106', now(), now()),
	(uuid(), 'GX 460', 'GX 460', '106', now(), now()),
	(uuid(), 'LX 570', 'LX 570', '106', now(), now()),
	(uuid(), 'RX 450', 'RX 450', '106', now(), now()),
	(uuid(), 'ES 300H', 'ES 300H', '106', now(), now()),
	(uuid(), 'GS 200T', 'GS 200T', '106', now(), now()),
	(uuid(), 'LS 430', 'LS 430', '106', now(), now()),
	(uuid(), 'RC 350', 'RC 350', '106', now(), now()),
	(uuid(), 'NX 300', 'NX 300', '106', now(), now()),
	(uuid(), 'LS 500', 'LS 500', '106', now(), now()),
	(uuid(), 'NX 200T', 'NX 200T', '106', now(), now()),
	(uuid(), 'RX 350L', 'RX 350L', '106', now(), now()),
	(uuid(), 'UX 200', 'UX 200', '106', now(), now()),
	(uuid(), 'LS 460L', 'LS 460L', '106', now(), now()),
	(uuid(), 'LC 500', 'LC 500', '106', now(), now()),
	(uuid(), 'RC F', 'RC F', '106', now(), now()),
	(uuid(), 'RX 450H', 'RX 450H', '106', now(), now()),
	(uuid(), 'NX 350', 'NX 350', '106', now(), now()),
	(uuid(), 'IS 500', 'IS 500', '106', now(), now()),
	(uuid(), 'CX-9', 'CX-9', '107', now(), now()),
	(uuid(), '1', '1', '107', now(), now()),
	(uuid(), '2', '2', '107', now(), now()),
	(uuid(), 'CX-7', 'CX-7', '107', now(), now()),
	(uuid(), 'MX-5', 'MX-5', '107', now(), now()),
	(uuid(), 'MAZDA 6', 'MAZDA 6', '107', now(), now()),
	(uuid(), 'MAZDA 3', 'MAZDA 3', '107', now(), now()),
	(uuid(), 'L/TRUCK', 'L/TRUCK', '108', now(), now()),
	(uuid(), '720E37', '720E37', '108', now(), now()),
	(uuid(), '450', '450', '108', now(), now()),
	(uuid(), '75E16', '75E16', '108', now(), now()),
	(uuid(), '120E28', '120E28', '108', now(), now()),
	(uuid(), '360,', '360,', '108', now(), now()),
	(uuid(), '460', '460', '108', now(), now()),
	(uuid(), '430.', '430.', '108', now(), now()),
	(uuid(), '120E25', '120E25', '108', now(), now()),
	(uuid(), '400 E6', '400 E6', '108', now(), now()),
	(uuid(), '420', '420', '108', now(), now()),
	(uuid(), 'TRAKKER 480', 'TRAKKER 480', '108', now(), now()),
	(uuid(), '308', '308', '109', now(), now()),
	(uuid(), '107', '107', '109', now(), now()),
	(uuid(), '208', '208', '109', now(), now()),
	(uuid(), '408', '408', '109', now(), now()),
	(uuid(), '508', '508', '109', now(), now()),
	(uuid(), '504', '504', '109', now(), now()),
	(uuid(), '307', '307', '109', now(), now()),
	(uuid(), 'WRX', 'WRX', '113', now(), now()),
	(uuid(), 'XV', 'XV', '113', now(), now()),
	(uuid(), 'LEGACY', 'LEGACY', '113', now(), now()),
	(uuid(), 'TERIOS', 'TERIOS', '114', now(), now()),
	(uuid(), 'SIRION', 'SIRION', '114', now(), now()),
	(uuid(), 'QX60', 'QX60', '118', now(), now()),
	(uuid(), 'G37', 'G37', '118', now(), now()),
	(uuid(), '440', '440', '118', now(), now()),
	(uuid(), 'EX 35', 'EX 35', '118', now(), now()),
	(uuid(), 'G37 S', 'G37 S', '118', now(), now()),
	(uuid(), 'QX 56', 'QX 56', '118', now(), now()),
	(uuid(), 'G35 X', 'G35 X', '118', now(), now()),
	(uuid(), 'Q 35', 'Q 35', '118', now(), now()),
	(uuid(), 'Q-70', 'Q-70', '118', now(), now()),
	(uuid(), 'Q-50', 'Q-50', '118', now(), now()),
	(uuid(), 'QX50', 'QX50', '118', now(), now()),
	(uuid(), 'QX30', 'QX30', '118', now(), now()),
	(uuid(), 'G37 X', 'G37 X', '118', now(), now()),
	(uuid(), 'SMALL BUS', 'SMALL BUS', '120', now(), now()),
	(uuid(), '4231', '4231', '121', now(), now()),
	(uuid(), '84 44', '84 44', '121', now(), now()),
	(uuid(), 'E1REWARD', 'E1REWARD', '123', now(), now()),
	(uuid(), 'REWARD', 'REWARD', '123', now(), now()),
	(uuid(), 'D-MAX', 'D-MAX', '123', now(), now()),
	(uuid(), '1022', '1022', '125', now(), now()),
	(uuid(), '1025', '1025', '125', now(), now()),
	(uuid(), '650.', '650.', '125', now(), now()),
	(uuid(), '820', '820', '125', now(), now()),
	(uuid(), 'X80', 'X80', '125', now(), now()),
	(uuid(), 'X70', 'X70', '125', now(), now()),
	(uuid(), 'X50', 'X50', '125', now(), now()),
	(uuid(), 'X50II', 'X50II', '125', now(), now()),
	(uuid(), 'X7', 'X7', '125', now(), now()),
	(uuid(), 'SEASION', 'SEASION', '125', now(), now()),
	(uuid(), 'FOISON.', 'FOISON.', '125', now(), now()),
	(uuid(), '330EV', '330EV', '125', now(), now()),
	(uuid(), '650EV', '650EV', '125', now(), now()),
	(uuid(), 'C30E', 'C30E', '125', now(), now()),
	(uuid(), 'M7', 'M7', '125', now(), now()),
	(uuid(), 'HUNTER', 'HUNTER', '126', now(), now()),
	(uuid(), 'R 400', 'R 400', '127', now(), now()),
	(uuid(), 'G80', 'G80', '128', now(), now()),
	(uuid(), 'G90', 'G90', '128', now(), now()),
	(uuid(), 'G70', 'G70', '128', now(), now()),
	(uuid(), 'G90L', 'G90L', '128', now(), now()),
	(uuid(), 'GV70', 'GV70', '128', now(), now()),
	(uuid(), 'GV80', 'GV80', '128', now(), now()),
	(uuid(), 'EQ900', 'EQ900', '128', now(), now()),
	(uuid(), 'ZK6729D', 'ZK6729D', '129', now(), now()),
	(uuid(), 'WERSTAR', 'WERSTAR', '130', now(), now()),
	(uuid(), 'COOPER,S', 'COOPER,S', '131', now(), now());