export const countries = [
  { id: 1, name: "Afghanistan", description: "أفغانستان" },
  { id: 2, name: "Albania", description: "ألبانيا" },
  { id: 3, name: "Algeria", description: "الجزائر" },
  { id: 4, name: "Andorra", description: "أندورا" },
  { id: 5, name: "Angola", description: "أنغولا" },
  { id: 6, name: "Antigua and Barbuda", description: "أنتيغوا وبربودا" },
  { id: 7, name: "Argentina", description: "الأرجنتين" },
  { id: 8, name: "Armenia", description: "أرمينيا" },
  { id: 9, name: "Australia", description: "أستراليا" },
  { id: 10, name: "Austria", description: "النمسا" },
  { id: 11, name: "Azerbaijan", description: "أذربيجان" },
  { id: 12, name: "Bahamas", description: "جزر البهاما" },
  { id: 13, name: "Bahrain", description: "البحرين" },
  { id: 14, name: "Bangladesh", description: "بنغلاديش" },
  { id: 15, name: "Barbados", description: "بربادوس" },
  { id: 16, name: "Belarus", description: "روسيا البيضاء" },
  { id: 17, name: "Belgium", description: "بلجيكا" },
  { id: 18, name: "Belize", description: "بليز" },
  { id: 19, name: "Benin", description: "بنين" },
  { id: 20, name: "Bhutan", description: "بوتان" },
  { id: 21, name: "Bolivia", description: "بوليفيا" },
  { id: 22, name: "Bosnia and Herzegovina", description: "البوسنة والهرسك" },
  { id: 23, name: "Botswana", description: "بتسوانا" },
  { id: 24, name: "Brazil", description: "البرازيل" },
  { id: 25, name: "Brunei", description: "بروناي" },
  { id: 26, name: "Bulgaria", description: "بلغاريا" },
  { id: 27, name: "Burkina Faso", description: "بوركينا فاسو" },
  { id: 28, name: "Burundi", description: "بوروندي" },
  { id: 29, name: "Cabo Verde", description: "كابو فيردي" },
  { id: 30, name: "Cambodia", description: "كمبوديا" },
  { id: 31, name: "Cameroon", description: "الكاميرون" },
  { id: 32, name: "Canada", description: "كندا" },
  {
    id: 33,
    name: "Central African Republic",
    description: "جمهورية افريقيا الوسطى",
  },
  { id: 34, name: "Chad", description: "تشاد" },
  { id: 35, name: "Chile", description: "تشيلي" },
  { id: 36, name: "China", description: "الصين" },
  { id: 37, name: "Colombia", description: "كولومبيا" },
  { id: 38, name: "Costa Rica", description: "كوستاريكا" },
  { id: 39, name: "Croatia", description: "كرواتيا" },
  { id: 40, name: "Cuba", description: "كوبا" },
  { id: 41, name: "Cyprus", description: "قبرص" },
  { id: 42, name: "Czech Republic", description: "جمهورية التشيك" },
  { id: 43, name: "Denmark", description: "الدنمارك" },
  { id: 44, name: "Djibouti", description: "جيبوتي" },
  { id: 45, name: "Dominica", description: "دومينيكا" },
  { id: 46, name: "Dominican Republic", description: "جمهورية الدومينيكان" },
  { id: 47, name: "Ecuador", description: "الاكوادور" },
  { id: 48, name: "Egypt", description: "مصر" },
  { id: 49, name: "El Salvador", description: "السلفادور" },
  { id: 50, name: "Equatorial Guinea", description: "غينيا الاستوائية" },
  { id: 51, name: "Eritrea", description: "إريتريا" },
  { id: 52, name: "Estonia", description: "استونيا" },
  { id: 53, name: "Ethiopia", description: "إثيوبيا" },
  { id: 54, name: "Fiji", description: "فيجي" },
  { id: 55, name: "Finland", description: "فنلندا" },
  { id: 56, name: "France", description: "فرنسا" },
  { id: 57, name: "Gabon", description: "الجابون" },
  { id: 58, name: "Gambia", description: "غامبيا" },
  { id: 59, name: "Georgia", description: "جورجيا" },
  { id: 60, name: "Germany", description: "ألمانيا" },
  { id: 61, name: "Ghana", description: "غانا" },
  { id: 62, name: "Greece", description: "اليونان" },
  { id: 63, name: "Grenada", description: "غرينادا" },
  { id: 64, name: "Guatemala", description: "غواتيمالا" },
  { id: 65, name: "Guinea", description: "غينيا" },
  { id: 66, name: "Guinea-Bissau", description: "غينيا بيساو" },
  { id: 67, name: "Guyana", description: "غيانا" },
  { id: 68, name: "Haiti", description: "هايتي" },
  { id: 69, name: "Honduras", description: "هندوراس" },
  { id: 70, name: "Hungary", description: "هنغاريا" },
  { id: 71, name: "Iceland", description: "أيسلندا" },
  { id: 72, name: "India", description: "الهند" },
  { id: 73, name: "Indonesia", description: "إندونيسيا" },
  { id: 74, name: "Iran", description: "إيران" },
  { id: 75, name: "Iraq", description: "العراق" },
  { id: 76, name: "Ireland", description: "إيرلندا" },
  { id: 77, name: "Israel", description: "إسرائيل" },
  { id: 78, name: "Italy", description: "إيطاليا" },
  { id: 79, name: "Jamaica", description: "جامايكا" },
  { id: 80, name: "Japan", description: "اليابان" },
  { id: 81, name: "Jordan", description: "الأردن" },
  { id: 82, name: "Kazakhstan", description: "كازاخستان" },
  { id: 83, name: "Kenya", description: "كينيا" },
  { id: 84, name: "Kiribati", description: "كيريباتي" },
  { id: 85, name: "Kuwait", description: "الكويت" },
  { id: 86, name: "Kyrgyzstan", description: "قيرغيزستان" },
  { id: 87, name: "Laos", description: "لاوس" },
  { id: 88, name: "Latvia", description: "لاتفيا" },
  { id: 89, name: "Lebanon", description: "لبنان" },
  { id: 90, name: "Lesotho", description: "ليسوتو" },
  { id: 91, name: "Liberia", description: "ليبريا" },
  { id: 92, name: "Libya", description: "ليبيا" },
  { id: 93, name: "Liechtenstein", description: "ليختنشتاين" },
  { id: 94, name: "Lithuania", description: "ليتوانيا" },
  { id: 95, name: "Luxembourg", description: "لوكسمبورج" },
  { id: 96, name: "Macedonia", description: "مقدونيا" },
  { id: 97, name: "Madagascar", description: "ماداجيدا" },
  { id: 98, name: "Malawi", description: "مالاوي" },
  { id: 99, name: "Malaysia", description: "ماليزيا" },
  { id: 100, name: "Maldives", description: "مالديف" },
  { id: 101, name: "Mali", description: "مالي" },
  { id: 102, name: "Malta", description: "مالطا" },
  { id: 103, name: "Mauritania", description: "موريتانيا" },
  { id: 104, name: "Mauritius", description: "موريشيوس" },
  { id: 105, name: "Mexico", description: "المكسيك" },
  { id: 106, name: "Moldova", description: "مولدافيا" },
  { id: 107, name: "Monaco", description: "موناكو" },
  { id: 108, name: "Mongolia", description: "منغوليا" },
  { id: 109, name: "Montenegro", description: "مونتشرين" },
  { id: 110, name: "Morocco", description: "المغرب" },
  { id: 111, name: "Mozambique", description: "موزامبيق" },
  { id: 112, name: "Namibia", description: "ناميبيا" },
  { id: 113, name: "Nepal", description: "نيبال" },
  { id: 114, name: "Netherlands", description: "هولندا" },
  { id: 115, name: "New Zealand", description: "نيوزيلاندا" },
  { id: 116, name: "Nicaragua", description: "نيكاراغوا" },
  { id: 117, name: "Niger", description: "النيجر" },
  { id: 118, name: "Nigeria", description: "نيجيريا" },
  { id: 119, name: "Norway", description: "نرويج" },
  { id: 120, name: "Oman", description: "عمان" },
  { id: 121, name: "Pakistan", description: "باكستان" },
  { id: 122, name: "Panama", description: "باناما" },
  { id: 123, name: "Paraguay", description: "باراغواي" },
  { id: 124, name: "Peru", description: "بيرو" },
  { id: 125, name: "Philippines", description: "فيليبينيا" },
  { id: 126, name: "Poland", description: "بولندا" },
  { id: 127, name: "Portugal", description: "بولتينيز" },
  { id: 128, name: "Qatar", description: "قطر" },
  { id: 129, name: "Romania", description: "رومانيا" },
  { id: 130, name: "Russia", description: "روسيا" },
  { id: 131, name: "Rwanda", description: "رواندا" },
  { id: 132, name: "Samoa", description: "ساموا" },
  { id: 133, name: "San Marino", description: "سان مارينو" },
  { id: 134, name: "Saudi Arabia", description: "المملكة العربية السعودية" },
  { id: 135, name: "Senegal", description: "سنغال" },
  { id: 136, name: "Serbia", description: "صربيا" },
  { id: 137, name: "Seychelles", description: "سيشيل" },
  { id: 138, name: "Sierra Leone", description: "سيراليون" },
  { id: 139, name: "Singapore", description: "سنغافورة" },
  { id: 140, name: "Slovakia", description: "سلوفاكيا" },
  { id: 142, name: "Solomon Islands", description: "جزر سليمان" },
  { id: 143, name: "Somalia", description: "سوماليا" },
  { id: 144, name: "South Africa", description: "جنوب أفريقيا" },
  { id: 145, name: "Spain", description: "إسبانيا" },
  { id: 146, name: "Sri Lanka", description: "سريلانكا" },
  { id: 147, name: "Sudan", description: "سودان" },
  { id: 148, name: "Suriname", description: "سورينام" },
  { id: 149, name: "Swaziland", description: "سوازيلاند" },
  { id: 150, name: "Sweden", description: "السويد" },
  { id: 151, name: "Switzerland", description: "سويسرا" },
  { id: 152, name: "Syria", description: "سوريا" },
  { id: 153, name: "Taiwan", description: "تايوان" },
  { id: 154, name: "Tajikistan", description: "تاجيكستان" },
  { id: 155, name: "Thailand", description: "تايلاند" },
  { id: 156, name: "Togo", description: "توغو" },
  { id: 157, name: "Tunisia", description: "تونس" },
  { id: 158, name: "Turkey", description: "تركيا" },
  { id: 159, name: "Turkmenistan", description: "تركمانستان" },
  { id: 160, name: "Ukraine", description: "أوكرانيا" },
  {
    id: 161,
    name: "United Arab Emirates",
    description: "الإمارات العربية المتحدة",
  },
  { id: 162, name: "United Kingdom", description: "المملكة المتحدة" },
  {
    id: 163,
    name: "United States",
    description: "الولايات المتحدة الأمريكية",
  },
  { id: 164, name: "Uruguay", description: "أوروغواي" },
  { id: 165, name: "Uzbekistan", description: "أوزباكستان" },
  { id: 166, name: "Venezuela", description: "فنزويليا" },
  { id: 167, name: "Vietnam", description: "فيتنام" },
  { id: 168, name: "Yemen", description: "اليمن" },
  { id: 169, name: "Zambia", description: "زامبيا" },
  { id: 170, name: "Zimbabwe", description: "زيمبابوي" },
  { id: 171, name: "South Korea", description: "كوريا الجنوبية" },
  { id: 172, name: "North Korea", description: "كوريا الشمالية" },
];
