export const ports = [
  {
    id: 1,
    name: "Salawa",
    description: "سلوى",
    code: "41",
  },
  {
    id: 2,
    name: "Khafji",
    description: "الخفجي",
    code: "44",
  },
  {
    id: 3,
    name: "Batha",
    description: "البطحاء",
    code: "31",
  },
  {
    id: 4,
    name: "King Abduliz Seaport",
    description: "ميناء الملك عبدالعزيز",
    code: "30",
  },
  {
    id: 5,
    name: "Jeddah Islamic Seaport",
    description: "ميناء جدة الإسلامي",
    code: "10",
  },
  {
    id: 6,
    name: "King Fahad Causeway",
    description: "جسر الملك فهد",
    code: "83",
  },
  {
    id: 7,
    name: "Ruqai",
    description: "الرقعي",
    code: "35",
  },
  {
    id: 8,
    name: "Yanbu Seaport",
    description: "ميناء ينبع",
    code: "",
  },
  {
    id: 9,
    name: "Jubail Seaport",
    description: "محافظة الجبيل",
    code: "",
  },
  {
    id: 10,
    name: "RasTanoorah Seaport",
    description: "ميناء راس تنورة",
    code: "",
  },
  {
    id: 11,
    name: "King Abdulah Seaport",
    description: "ميناء الملك عبدالله",
    code: "",
  },
  {
    id: 12,
    name: "Diba Seaport",
    description: "ميناء ضباء",
    code: "",
  },
  {
    id: 13,
    name: "Jaizan Seaport",
    description: "ميناء جازان",
    code: "",
  },
  {
    id: 14,
    name: "Fursan Seaport",
    description: "ميناء فرسان",
    code: "",
  },
  {
    id: 15,
    name: "Dry port",
    description: "الرياض الميناء الجاف",
    code: "",
  },
  {
    id: 16,
    name: "Halt Ammar",
    description: "حالة عمار",
    code: "",
  },
  {
    id: 17,
    name: "Durah",
    description: "الدرة",
    code: "",
  },
  {
    id: 18,
    name: "JadedatArar",
    description: "جديدة عرعر",
    code: "",
  },
  {
    id: 19,
    name: "Turaif",
    description: "طريف",
    code: "",
  },
  {
    id: 20,
    name: "Haditha",
    description: "الحديثة",
    code: "",
  },
  {
    id: 21,
    name: "Twal",
    description: "الطوال",
    code: "",
  },
  {
    id: 22,
    name: "Khadar",
    description: "الخضراء",
    code: "",
  },
  {
    id: 23,
    name: "Alab",
    description: "علب",
    code: "",
  },
  {
    id: 24,
    name: "wadya",
    description: "الوديعة",
    code: "",
  },
  {
    id: 25,
    name: "King Fahd AirPort",
    description: "مطار الملك فهد",
    code: "",
  },
];
